// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: backend/internal/realtimepb/realtime.proto

package realtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClickRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	ComboCount    int64                  `protobuf:"varint,2,opt,name=combo_count,json=comboCount,proto3" json:"combo_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *ClickRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ClickRequest) GetComboCount() int64 {
	if x != nil {
		return x.ComboCount
	}
	return 0
}

type ClickAck struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Delta                int64                  `protobuf:"varint,1,opt,name=delta,proto3" json:"delta,omitempty"`
	Critical             bool                   `protobuf:"varint,2,opt,name=critical,proto3" json:"critical,omitempty"`
	BossDamage           int64                  `protobuf:"varint,3,opt,name=boss_damage,json=bossDamage,proto3" json:"boss_damage,omitempty"`
	MyBossDamage         int64                  `protobuf:"varint,4,opt,name=my_boss_damage,json=myBossDamage,proto3" json:"my_boss_damage,omitempty"`
	BossLeaderboardCount int32                  `protobuf:"varint,5,opt,name=boss_leaderboard_count,json=bossLeaderboardCount,proto3" json:"boss_leaderboard_count,omitempty"`
	DamageType           string                 `protobuf:"bytes,6,opt,name=damage_type,json=damageType,proto3" json:"damage_type,omitempty"`
	TalentEvents         []*TalentTriggerEvent  `protobuf:"bytes,7,rep,name=talent_events,json=talentEvents,proto3" json:"talent_events,omitempty"`
	PartStateDeltas      []*BossPartStateDelta  `protobuf:"bytes,8,rep,name=part_state_deltas,json=partStateDeltas,proto3" json:"part_state_deltas,omitempty"`
	TalentCombatState    *TalentCombatState     `protobuf:"bytes,9,opt,name=talent_combat_state,json=talentCombatState,proto3" json:"talent_combat_state,omitempty"`
	UserDelta            *UserDeltaPatch        `protobuf:"bytes,10,opt,name=user_delta,json=userDelta,proto3" json:"user_delta,omitempty"`
	Button               *ButtonRef             `protobuf:"bytes,11,opt,name=button,proto3" json:"button,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ClickAck) Reset() {
	*x = ClickAck{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickAck) ProtoMessage() {}

func (x *ClickAck) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickAck.ProtoReflect.Descriptor instead.
func (*ClickAck) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *ClickAck) GetDelta() int64 {
	if x != nil {
		return x.Delta
	}
	return 0
}

func (x *ClickAck) GetCritical() bool {
	if x != nil {
		return x.Critical
	}
	return false
}

func (x *ClickAck) GetBossDamage() int64 {
	if x != nil {
		return x.BossDamage
	}
	return 0
}

func (x *ClickAck) GetMyBossDamage() int64 {
	if x != nil {
		return x.MyBossDamage
	}
	return 0
}

func (x *ClickAck) GetBossLeaderboardCount() int32 {
	if x != nil {
		return x.BossLeaderboardCount
	}
	return 0
}

func (x *ClickAck) GetDamageType() string {
	if x != nil {
		return x.DamageType
	}
	return ""
}

func (x *ClickAck) GetTalentEvents() []*TalentTriggerEvent {
	if x != nil {
		return x.TalentEvents
	}
	return nil
}

func (x *ClickAck) GetPartStateDeltas() []*BossPartStateDelta {
	if x != nil {
		return x.PartStateDeltas
	}
	return nil
}

func (x *ClickAck) GetTalentCombatState() *TalentCombatState {
	if x != nil {
		return x.TalentCombatState
	}
	return nil
}

func (x *ClickAck) GetUserDelta() *UserDeltaPatch {
	if x != nil {
		return x.UserDelta
	}
	return nil
}

func (x *ClickAck) GetButton() *ButtonRef {
	if x != nil {
		return x.Button
	}
	return nil
}

type UserDeltaPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`
	Stones        int64                  `protobuf:"varint,2,opt,name=stones,proto3" json:"stones,omitempty"`
	TalentPoints  int64                  `protobuf:"varint,3,opt,name=talent_points,json=talentPoints,proto3" json:"talent_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDeltaPatch) Reset() {
	*x = UserDeltaPatch{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDeltaPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDeltaPatch) ProtoMessage() {}

func (x *UserDeltaPatch) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDeltaPatch.ProtoReflect.Descriptor instead.
func (*UserDeltaPatch) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *UserDeltaPatch) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UserDeltaPatch) GetStones() int64 {
	if x != nil {
		return x.Stones
	}
	return 0
}

func (x *UserDeltaPatch) GetTalentPoints() int64 {
	if x != nil {
		return x.TalentPoints
	}
	return 0
}

type ButtonRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ButtonRef) Reset() {
	*x = ButtonRef{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ButtonRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ButtonRef) ProtoMessage() {}

func (x *ButtonRef) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ButtonRef.ProtoReflect.Descriptor instead.
func (*ButtonRef) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{3}
}

func (x *ButtonRef) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type PublicDelta struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	TotalVotes          int64                   `protobuf:"varint,1,opt,name=total_votes,json=totalVotes,proto3" json:"total_votes,omitempty"`
	Leaderboard         []*LeaderboardEntry     `protobuf:"bytes,2,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	RoomId              string                  `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Boss                *Boss                   `protobuf:"bytes,4,opt,name=boss,proto3" json:"boss,omitempty"`
	BossLeaderboard     []*BossLeaderboardEntry `protobuf:"bytes,5,rep,name=boss_leaderboard,json=bossLeaderboard,proto3" json:"boss_leaderboard,omitempty"`
	AnnouncementVersion string                  `protobuf:"bytes,6,opt,name=announcement_version,json=announcementVersion,proto3" json:"announcement_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PublicDelta) Reset() {
	*x = PublicDelta{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicDelta) ProtoMessage() {}

func (x *PublicDelta) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicDelta.ProtoReflect.Descriptor instead.
func (*PublicDelta) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{4}
}

func (x *PublicDelta) GetTotalVotes() int64 {
	if x != nil {
		return x.TotalVotes
	}
	return 0
}

func (x *PublicDelta) GetLeaderboard() []*LeaderboardEntry {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *PublicDelta) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *PublicDelta) GetBoss() *Boss {
	if x != nil {
		return x.Boss
	}
	return nil
}

func (x *PublicDelta) GetBossLeaderboard() []*BossLeaderboardEntry {
	if x != nil {
		return x.BossLeaderboard
	}
	return nil
}

func (x *PublicDelta) GetAnnouncementVersion() string {
	if x != nil {
		return x.AnnouncementVersion
	}
	return ""
}

type PublicMeta struct {
	state               protoimpl.MessageState  `protogen:"open.v1"`
	Leaderboard         []*LeaderboardEntry     `protobuf:"bytes,1,rep,name=leaderboard,proto3" json:"leaderboard,omitempty"`
	BossLeaderboard     []*BossLeaderboardEntry `protobuf:"bytes,2,rep,name=boss_leaderboard,json=bossLeaderboard,proto3" json:"boss_leaderboard,omitempty"`
	AnnouncementVersion string                  `protobuf:"bytes,3,opt,name=announcement_version,json=announcementVersion,proto3" json:"announcement_version,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PublicMeta) Reset() {
	*x = PublicMeta{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicMeta) ProtoMessage() {}

func (x *PublicMeta) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicMeta.ProtoReflect.Descriptor instead.
func (*PublicMeta) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{5}
}

func (x *PublicMeta) GetLeaderboard() []*LeaderboardEntry {
	if x != nil {
		return x.Leaderboard
	}
	return nil
}

func (x *PublicMeta) GetBossLeaderboard() []*BossLeaderboardEntry {
	if x != nil {
		return x.BossLeaderboard
	}
	return nil
}

func (x *PublicMeta) GetAnnouncementVersion() string {
	if x != nil {
		return x.AnnouncementVersion
	}
	return ""
}

type RoomInfo struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Id                       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DisplayName              string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Current                  bool                   `protobuf:"varint,3,opt,name=current,proto3" json:"current,omitempty"`
	Joinable                 bool                   `protobuf:"varint,4,opt,name=joinable,proto3" json:"joinable,omitempty"`
	OnlineCount              int32                  `protobuf:"varint,5,opt,name=online_count,json=onlineCount,proto3" json:"online_count,omitempty"`
	CycleEnabled             bool                   `protobuf:"varint,6,opt,name=cycle_enabled,json=cycleEnabled,proto3" json:"cycle_enabled,omitempty"`
	QueueId                  string                 `protobuf:"bytes,7,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	CurrentBossId            string                 `protobuf:"bytes,8,opt,name=current_boss_id,json=currentBossId,proto3" json:"current_boss_id,omitempty"`
	CurrentBossName          string                 `protobuf:"bytes,9,opt,name=current_boss_name,json=currentBossName,proto3" json:"current_boss_name,omitempty"`
	CurrentBossStatus        string                 `protobuf:"bytes,10,opt,name=current_boss_status,json=currentBossStatus,proto3" json:"current_boss_status,omitempty"`
	CurrentBossHp            int64                  `protobuf:"varint,11,opt,name=current_boss_hp,json=currentBossHp,proto3" json:"current_boss_hp,omitempty"`
	CurrentBossMaxHp         int64                  `protobuf:"varint,12,opt,name=current_boss_max_hp,json=currentBossMaxHp,proto3" json:"current_boss_max_hp,omitempty"`
	CurrentBossAvgHp         int64                  `protobuf:"varint,13,opt,name=current_boss_avg_hp,json=currentBossAvgHp,proto3" json:"current_boss_avg_hp,omitempty"`
	CooldownRemainingSeconds int64                  `protobuf:"varint,14,opt,name=cooldown_remaining_seconds,json=cooldownRemainingSeconds,proto3" json:"cooldown_remaining_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{6}
}

func (x *RoomInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RoomInfo) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RoomInfo) GetCurrent() bool {
	if x != nil {
		return x.Current
	}
	return false
}

func (x *RoomInfo) GetJoinable() bool {
	if x != nil {
		return x.Joinable
	}
	return false
}

func (x *RoomInfo) GetOnlineCount() int32 {
	if x != nil {
		return x.OnlineCount
	}
	return 0
}

func (x *RoomInfo) GetCycleEnabled() bool {
	if x != nil {
		return x.CycleEnabled
	}
	return false
}

func (x *RoomInfo) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *RoomInfo) GetCurrentBossId() string {
	if x != nil {
		return x.CurrentBossId
	}
	return ""
}

func (x *RoomInfo) GetCurrentBossName() string {
	if x != nil {
		return x.CurrentBossName
	}
	return ""
}

func (x *RoomInfo) GetCurrentBossStatus() string {
	if x != nil {
		return x.CurrentBossStatus
	}
	return ""
}

func (x *RoomInfo) GetCurrentBossHp() int64 {
	if x != nil {
		return x.CurrentBossHp
	}
	return 0
}

func (x *RoomInfo) GetCurrentBossMaxHp() int64 {
	if x != nil {
		return x.CurrentBossMaxHp
	}
	return 0
}

func (x *RoomInfo) GetCurrentBossAvgHp() int64 {
	if x != nil {
		return x.CurrentBossAvgHp
	}
	return 0
}

func (x *RoomInfo) GetCooldownRemainingSeconds() int64 {
	if x != nil {
		return x.CooldownRemainingSeconds
	}
	return 0
}

type RoomState struct {
	state                          protoimpl.MessageState `protogen:"open.v1"`
	CurrentRoomId                  string                 `protobuf:"bytes,1,opt,name=current_room_id,json=currentRoomId,proto3" json:"current_room_id,omitempty"`
	SwitchCooldownRemainingSeconds int64                  `protobuf:"varint,2,opt,name=switch_cooldown_remaining_seconds,json=switchCooldownRemainingSeconds,proto3" json:"switch_cooldown_remaining_seconds,omitempty"`
	Rooms                          []*RoomInfo            `protobuf:"bytes,3,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *RoomState) Reset() {
	*x = RoomState{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomState) ProtoMessage() {}

func (x *RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomState.ProtoReflect.Descriptor instead.
func (*RoomState) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{7}
}

func (x *RoomState) GetCurrentRoomId() string {
	if x != nil {
		return x.CurrentRoomId
	}
	return ""
}

func (x *RoomState) GetSwitchCooldownRemainingSeconds() int64 {
	if x != nil {
		return x.SwitchCooldownRemainingSeconds
	}
	return 0
}

func (x *RoomState) GetRooms() []*RoomInfo {
	if x != nil {
		return x.Rooms
	}
	return nil
}

type UserDelta struct {
	state                              protoimpl.MessageState `protogen:"open.v1"`
	UserStats                          *UserStats             `protobuf:"bytes,1,opt,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	MyBossStats                        *BossUserStats         `protobuf:"bytes,2,opt,name=my_boss_stats,json=myBossStats,proto3" json:"my_boss_stats,omitempty"`
	MyBossKills                        int64                  `protobuf:"varint,3,opt,name=my_boss_kills,json=myBossKills,proto3" json:"my_boss_kills,omitempty"`
	TotalBossKills                     int64                  `protobuf:"varint,4,opt,name=total_boss_kills,json=totalBossKills,proto3" json:"total_boss_kills,omitempty"`
	RoomId                             string                 `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Loadout                            *Loadout               `protobuf:"bytes,6,opt,name=loadout,proto3" json:"loadout,omitempty"`
	CombatStats                        *CombatStats           `protobuf:"bytes,7,opt,name=combat_stats,json=combatStats,proto3" json:"combat_stats,omitempty"`
	Gold                               int64                  `protobuf:"varint,8,opt,name=gold,proto3" json:"gold,omitempty"`
	Stones                             int64                  `protobuf:"varint,9,opt,name=stones,proto3" json:"stones,omitempty"`
	TalentPoints                       int64                  `protobuf:"varint,10,opt,name=talent_points,json=talentPoints,proto3" json:"talent_points,omitempty"`
	RecentRewards                      []*Reward              `protobuf:"bytes,11,rep,name=recent_rewards,json=recentRewards,proto3" json:"recent_rewards,omitempty"`
	TalentEvents                       []*TalentTriggerEvent  `protobuf:"bytes,12,rep,name=talent_events,json=talentEvents,proto3" json:"talent_events,omitempty"`
	TalentCombatState                  *TalentCombatState     `protobuf:"bytes,13,opt,name=talent_combat_state,json=talentCombatState,proto3" json:"talent_combat_state,omitempty"`
	EquippedBattleClickSkinId          string                 `protobuf:"bytes,14,opt,name=equipped_battle_click_skin_id,json=equippedBattleClickSkinId,proto3" json:"equipped_battle_click_skin_id,omitempty"`
	EquippedBattleClickCursorImagePath string                 `protobuf:"bytes,15,opt,name=equipped_battle_click_cursor_image_path,json=equippedBattleClickCursorImagePath,proto3" json:"equipped_battle_click_cursor_image_path,omitempty"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *UserDelta) Reset() {
	*x = UserDelta{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelta) ProtoMessage() {}

func (x *UserDelta) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelta.ProtoReflect.Descriptor instead.
func (*UserDelta) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{8}
}

func (x *UserDelta) GetUserStats() *UserStats {
	if x != nil {
		return x.UserStats
	}
	return nil
}

func (x *UserDelta) GetMyBossStats() *BossUserStats {
	if x != nil {
		return x.MyBossStats
	}
	return nil
}

func (x *UserDelta) GetMyBossKills() int64 {
	if x != nil {
		return x.MyBossKills
	}
	return 0
}

func (x *UserDelta) GetTotalBossKills() int64 {
	if x != nil {
		return x.TotalBossKills
	}
	return 0
}

func (x *UserDelta) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *UserDelta) GetLoadout() *Loadout {
	if x != nil {
		return x.Loadout
	}
	return nil
}

func (x *UserDelta) GetCombatStats() *CombatStats {
	if x != nil {
		return x.CombatStats
	}
	return nil
}

func (x *UserDelta) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *UserDelta) GetStones() int64 {
	if x != nil {
		return x.Stones
	}
	return 0
}

func (x *UserDelta) GetTalentPoints() int64 {
	if x != nil {
		return x.TalentPoints
	}
	return 0
}

func (x *UserDelta) GetRecentRewards() []*Reward {
	if x != nil {
		return x.RecentRewards
	}
	return nil
}

func (x *UserDelta) GetTalentEvents() []*TalentTriggerEvent {
	if x != nil {
		return x.TalentEvents
	}
	return nil
}

func (x *UserDelta) GetTalentCombatState() *TalentCombatState {
	if x != nil {
		return x.TalentCombatState
	}
	return nil
}

func (x *UserDelta) GetEquippedBattleClickSkinId() string {
	if x != nil {
		return x.EquippedBattleClickSkinId
	}
	return ""
}

func (x *UserDelta) GetEquippedBattleClickCursorImagePath() string {
	if x != nil {
		return x.EquippedBattleClickCursorImagePath
	}
	return ""
}

type UserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ClickCount    int64                  `protobuf:"varint,2,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserStats) Reset() {
	*x = UserStats{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserStats) ProtoMessage() {}

func (x *UserStats) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserStats.ProtoReflect.Descriptor instead.
func (*UserStats) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{9}
}

func (x *UserStats) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserStats) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	ClickCount    int64                  `protobuf:"varint,3,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{10}
}

func (x *LeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *LeaderboardEntry) GetClickCount() int64 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

type BossPart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ImagePath     string                 `protobuf:"bytes,5,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	MaxHp         int64                  `protobuf:"varint,6,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	CurrentHp     int64                  `protobuf:"varint,7,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	Armor         int64                  `protobuf:"varint,8,opt,name=armor,proto3" json:"armor,omitempty"`
	Alive         bool                   `protobuf:"varint,9,opt,name=alive,proto3" json:"alive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossPart) Reset() {
	*x = BossPart{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossPart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPart) ProtoMessage() {}

func (x *BossPart) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPart.ProtoReflect.Descriptor instead.
func (*BossPart) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{11}
}

func (x *BossPart) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BossPart) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BossPart) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BossPart) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *BossPart) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *BossPart) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *BossPart) GetCurrentHp() int64 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *BossPart) GetArmor() int64 {
	if x != nil {
		return x.Armor
	}
	return 0
}

func (x *BossPart) GetAlive() bool {
	if x != nil {
		return x.Alive
	}
	return false
}

type Boss struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TemplateId         string                 `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	RoomId             string                 `protobuf:"bytes,3,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	QueueId            string                 `protobuf:"bytes,4,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	Name               string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Status             string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	MaxHp              int64                  `protobuf:"varint,7,opt,name=max_hp,json=maxHp,proto3" json:"max_hp,omitempty"`
	CurrentHp          int64                  `protobuf:"varint,8,opt,name=current_hp,json=currentHp,proto3" json:"current_hp,omitempty"`
	GoldOnKill         int64                  `protobuf:"varint,9,opt,name=gold_on_kill,json=goldOnKill,proto3" json:"gold_on_kill,omitempty"`
	StoneOnKill        int64                  `protobuf:"varint,10,opt,name=stone_on_kill,json=stoneOnKill,proto3" json:"stone_on_kill,omitempty"`
	TalentPointsOnKill int64                  `protobuf:"varint,11,opt,name=talent_points_on_kill,json=talentPointsOnKill,proto3" json:"talent_points_on_kill,omitempty"`
	Parts              []*BossPart            `protobuf:"bytes,12,rep,name=parts,proto3" json:"parts,omitempty"`
	StartedAt          int64                  `protobuf:"varint,13,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	DefeatedAt         int64                  `protobuf:"varint,14,opt,name=defeated_at,json=defeatedAt,proto3" json:"defeated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Boss) Reset() {
	*x = Boss{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Boss) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Boss) ProtoMessage() {}

func (x *Boss) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Boss.ProtoReflect.Descriptor instead.
func (*Boss) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{12}
}

func (x *Boss) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Boss) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

func (x *Boss) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Boss) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *Boss) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Boss) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Boss) GetMaxHp() int64 {
	if x != nil {
		return x.MaxHp
	}
	return 0
}

func (x *Boss) GetCurrentHp() int64 {
	if x != nil {
		return x.CurrentHp
	}
	return 0
}

func (x *Boss) GetGoldOnKill() int64 {
	if x != nil {
		return x.GoldOnKill
	}
	return 0
}

func (x *Boss) GetStoneOnKill() int64 {
	if x != nil {
		return x.StoneOnKill
	}
	return 0
}

func (x *Boss) GetTalentPointsOnKill() int64 {
	if x != nil {
		return x.TalentPointsOnKill
	}
	return 0
}

func (x *Boss) GetParts() []*BossPart {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Boss) GetStartedAt() int64 {
	if x != nil {
		return x.StartedAt
	}
	return 0
}

func (x *Boss) GetDefeatedAt() int64 {
	if x != nil {
		return x.DefeatedAt
	}
	return 0
}

type BossLeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int32                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Damage        int64                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossLeaderboardEntry) Reset() {
	*x = BossLeaderboardEntry{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossLeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossLeaderboardEntry) ProtoMessage() {}

func (x *BossLeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossLeaderboardEntry.ProtoReflect.Descriptor instead.
func (*BossLeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{13}
}

func (x *BossLeaderboardEntry) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *BossLeaderboardEntry) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BossLeaderboardEntry) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type BossUserStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Damage        int64                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	Rank          int32                  `protobuf:"varint,3,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossUserStats) Reset() {
	*x = BossUserStats{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossUserStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossUserStats) ProtoMessage() {}

func (x *BossUserStats) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossUserStats.ProtoReflect.Descriptor instead.
func (*BossUserStats) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{14}
}

func (x *BossUserStats) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *BossUserStats) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *BossUserStats) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type InventoryItem struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ItemId               string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	InstanceId           string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Name                 string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Slot                 string                 `protobuf:"bytes,4,opt,name=slot,proto3" json:"slot,omitempty"`
	Rarity               string                 `protobuf:"bytes,5,opt,name=rarity,proto3" json:"rarity,omitempty"`
	ImagePath            string                 `protobuf:"bytes,6,opt,name=image_path,json=imagePath,proto3" json:"image_path,omitempty"`
	ImageAlt             string                 `protobuf:"bytes,7,opt,name=image_alt,json=imageAlt,proto3" json:"image_alt,omitempty"`
	Quantity             int64                  `protobuf:"varint,8,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Equipped             bool                   `protobuf:"varint,9,opt,name=equipped,proto3" json:"equipped,omitempty"`
	EnhanceLevel         int32                  `protobuf:"varint,10,opt,name=enhance_level,json=enhanceLevel,proto3" json:"enhance_level,omitempty"`
	Bound                bool                   `protobuf:"varint,11,opt,name=bound,proto3" json:"bound,omitempty"`
	Locked               bool                   `protobuf:"varint,12,opt,name=locked,proto3" json:"locked,omitempty"`
	AttackPower          int64                  `protobuf:"varint,13,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	ArmorPenPercent      float64                `protobuf:"fixed64,14,opt,name=armor_pen_percent,json=armorPenPercent,proto3" json:"armor_pen_percent,omitempty"`
	CritRate             float64                `protobuf:"fixed64,15,opt,name=crit_rate,json=critRate,proto3" json:"crit_rate,omitempty"`
	CritDamageMultiplier float64                `protobuf:"fixed64,16,opt,name=crit_damage_multiplier,json=critDamageMultiplier,proto3" json:"crit_damage_multiplier,omitempty"`
	PartTypeDamageSoft   float64                `protobuf:"fixed64,17,opt,name=part_type_damage_soft,json=partTypeDamageSoft,proto3" json:"part_type_damage_soft,omitempty"`
	PartTypeDamageHeavy  float64                `protobuf:"fixed64,18,opt,name=part_type_damage_heavy,json=partTypeDamageHeavy,proto3" json:"part_type_damage_heavy,omitempty"`
	PartTypeDamageWeak   float64                `protobuf:"fixed64,19,opt,name=part_type_damage_weak,json=partTypeDamageWeak,proto3" json:"part_type_damage_weak,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InventoryItem) Reset() {
	*x = InventoryItem{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InventoryItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryItem) ProtoMessage() {}

func (x *InventoryItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryItem.ProtoReflect.Descriptor instead.
func (*InventoryItem) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{15}
}

func (x *InventoryItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *InventoryItem) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InventoryItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InventoryItem) GetSlot() string {
	if x != nil {
		return x.Slot
	}
	return ""
}

func (x *InventoryItem) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *InventoryItem) GetImagePath() string {
	if x != nil {
		return x.ImagePath
	}
	return ""
}

func (x *InventoryItem) GetImageAlt() string {
	if x != nil {
		return x.ImageAlt
	}
	return ""
}

func (x *InventoryItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *InventoryItem) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

func (x *InventoryItem) GetEnhanceLevel() int32 {
	if x != nil {
		return x.EnhanceLevel
	}
	return 0
}

func (x *InventoryItem) GetBound() bool {
	if x != nil {
		return x.Bound
	}
	return false
}

func (x *InventoryItem) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *InventoryItem) GetAttackPower() int64 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *InventoryItem) GetArmorPenPercent() float64 {
	if x != nil {
		return x.ArmorPenPercent
	}
	return 0
}

func (x *InventoryItem) GetCritRate() float64 {
	if x != nil {
		return x.CritRate
	}
	return 0
}

func (x *InventoryItem) GetCritDamageMultiplier() float64 {
	if x != nil {
		return x.CritDamageMultiplier
	}
	return 0
}

func (x *InventoryItem) GetPartTypeDamageSoft() float64 {
	if x != nil {
		return x.PartTypeDamageSoft
	}
	return 0
}

func (x *InventoryItem) GetPartTypeDamageHeavy() float64 {
	if x != nil {
		return x.PartTypeDamageHeavy
	}
	return 0
}

func (x *InventoryItem) GetPartTypeDamageWeak() float64 {
	if x != nil {
		return x.PartTypeDamageWeak
	}
	return 0
}

type Loadout struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        *InventoryItem         `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	Helmet        *InventoryItem         `protobuf:"bytes,2,opt,name=helmet,proto3" json:"helmet,omitempty"`
	Chest         *InventoryItem         `protobuf:"bytes,3,opt,name=chest,proto3" json:"chest,omitempty"`
	Gloves        *InventoryItem         `protobuf:"bytes,4,opt,name=gloves,proto3" json:"gloves,omitempty"`
	Legs          *InventoryItem         `protobuf:"bytes,5,opt,name=legs,proto3" json:"legs,omitempty"`
	Accessory     *InventoryItem         `protobuf:"bytes,6,opt,name=accessory,proto3" json:"accessory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Loadout) Reset() {
	*x = Loadout{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Loadout) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Loadout) ProtoMessage() {}

func (x *Loadout) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Loadout.ProtoReflect.Descriptor instead.
func (*Loadout) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{16}
}

func (x *Loadout) GetWeapon() *InventoryItem {
	if x != nil {
		return x.Weapon
	}
	return nil
}

func (x *Loadout) GetHelmet() *InventoryItem {
	if x != nil {
		return x.Helmet
	}
	return nil
}

func (x *Loadout) GetChest() *InventoryItem {
	if x != nil {
		return x.Chest
	}
	return nil
}

func (x *Loadout) GetGloves() *InventoryItem {
	if x != nil {
		return x.Gloves
	}
	return nil
}

func (x *Loadout) GetLegs() *InventoryItem {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *Loadout) GetAccessory() *InventoryItem {
	if x != nil {
		return x.Accessory
	}
	return nil
}

type CombatStats struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	EffectiveIncrement    int64                  `protobuf:"varint,1,opt,name=effective_increment,json=effectiveIncrement,proto3" json:"effective_increment,omitempty"`
	NormalDamage          int64                  `protobuf:"varint,2,opt,name=normal_damage,json=normalDamage,proto3" json:"normal_damage,omitempty"`
	CriticalChancePercent float64                `protobuf:"fixed64,3,opt,name=critical_chance_percent,json=criticalChancePercent,proto3" json:"critical_chance_percent,omitempty"`
	CriticalDamage        int64                  `protobuf:"varint,4,opt,name=critical_damage,json=criticalDamage,proto3" json:"critical_damage,omitempty"`
	AttackPower           int64                  `protobuf:"varint,5,opt,name=attack_power,json=attackPower,proto3" json:"attack_power,omitempty"`
	ArmorPenPercent       float64                `protobuf:"fixed64,6,opt,name=armor_pen_percent,json=armorPenPercent,proto3" json:"armor_pen_percent,omitempty"`
	CritDamageMultiplier  float64                `protobuf:"fixed64,7,opt,name=crit_damage_multiplier,json=critDamageMultiplier,proto3" json:"crit_damage_multiplier,omitempty"`
	AllDamageAmplify      float64                `protobuf:"fixed64,8,opt,name=all_damage_amplify,json=allDamageAmplify,proto3" json:"all_damage_amplify,omitempty"`
	PartTypeDamageSoft    float64                `protobuf:"fixed64,9,opt,name=part_type_damage_soft,json=partTypeDamageSoft,proto3" json:"part_type_damage_soft,omitempty"`
	PartTypeDamageHeavy   float64                `protobuf:"fixed64,10,opt,name=part_type_damage_heavy,json=partTypeDamageHeavy,proto3" json:"part_type_damage_heavy,omitempty"`
	PartTypeDamageWeak    float64                `protobuf:"fixed64,11,opt,name=part_type_damage_weak,json=partTypeDamageWeak,proto3" json:"part_type_damage_weak,omitempty"`
	PerPartDamagePercent  float64                `protobuf:"fixed64,12,opt,name=per_part_damage_percent,json=perPartDamagePercent,proto3" json:"per_part_damage_percent,omitempty"`
	LowHpMultiplier       float64                `protobuf:"fixed64,13,opt,name=low_hp_multiplier,json=lowHpMultiplier,proto3" json:"low_hp_multiplier,omitempty"`
	LowHpThreshold        float64                `protobuf:"fixed64,14,opt,name=low_hp_threshold,json=lowHpThreshold,proto3" json:"low_hp_threshold,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CombatStats) Reset() {
	*x = CombatStats{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombatStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombatStats) ProtoMessage() {}

func (x *CombatStats) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombatStats.ProtoReflect.Descriptor instead.
func (*CombatStats) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{17}
}

func (x *CombatStats) GetEffectiveIncrement() int64 {
	if x != nil {
		return x.EffectiveIncrement
	}
	return 0
}

func (x *CombatStats) GetNormalDamage() int64 {
	if x != nil {
		return x.NormalDamage
	}
	return 0
}

func (x *CombatStats) GetCriticalChancePercent() float64 {
	if x != nil {
		return x.CriticalChancePercent
	}
	return 0
}

func (x *CombatStats) GetCriticalDamage() int64 {
	if x != nil {
		return x.CriticalDamage
	}
	return 0
}

func (x *CombatStats) GetAttackPower() int64 {
	if x != nil {
		return x.AttackPower
	}
	return 0
}

func (x *CombatStats) GetArmorPenPercent() float64 {
	if x != nil {
		return x.ArmorPenPercent
	}
	return 0
}

func (x *CombatStats) GetCritDamageMultiplier() float64 {
	if x != nil {
		return x.CritDamageMultiplier
	}
	return 0
}

func (x *CombatStats) GetAllDamageAmplify() float64 {
	if x != nil {
		return x.AllDamageAmplify
	}
	return 0
}

func (x *CombatStats) GetPartTypeDamageSoft() float64 {
	if x != nil {
		return x.PartTypeDamageSoft
	}
	return 0
}

func (x *CombatStats) GetPartTypeDamageHeavy() float64 {
	if x != nil {
		return x.PartTypeDamageHeavy
	}
	return 0
}

func (x *CombatStats) GetPartTypeDamageWeak() float64 {
	if x != nil {
		return x.PartTypeDamageWeak
	}
	return 0
}

func (x *CombatStats) GetPerPartDamagePercent() float64 {
	if x != nil {
		return x.PerPartDamagePercent
	}
	return 0
}

func (x *CombatStats) GetLowHpMultiplier() float64 {
	if x != nil {
		return x.LowHpMultiplier
	}
	return 0
}

func (x *CombatStats) GetLowHpThreshold() float64 {
	if x != nil {
		return x.LowHpThreshold
	}
	return 0
}

type Reward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BossId        string                 `protobuf:"bytes,1,opt,name=boss_id,json=bossId,proto3" json:"boss_id,omitempty"`
	BossName      string                 `protobuf:"bytes,2,opt,name=boss_name,json=bossName,proto3" json:"boss_name,omitempty"`
	ItemId        string                 `protobuf:"bytes,3,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,4,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	GrantedAt     int64                  `protobuf:"varint,5,opt,name=granted_at,json=grantedAt,proto3" json:"granted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reward) Reset() {
	*x = Reward{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reward) ProtoMessage() {}

func (x *Reward) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reward.ProtoReflect.Descriptor instead.
func (*Reward) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{18}
}

func (x *Reward) GetBossId() string {
	if x != nil {
		return x.BossId
	}
	return ""
}

func (x *Reward) GetBossName() string {
	if x != nil {
		return x.BossName
	}
	return ""
}

func (x *Reward) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Reward) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *Reward) GetGrantedAt() int64 {
	if x != nil {
		return x.GrantedAt
	}
	return 0
}

type TalentTriggerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TalentId      string                 `protobuf:"bytes,1,opt,name=talent_id,json=talentId,proto3" json:"talent_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	EffectType    string                 `protobuf:"bytes,3,opt,name=effect_type,json=effectType,proto3" json:"effect_type,omitempty"`
	ExtraDamage   int64                  `protobuf:"varint,4,opt,name=extra_damage,json=extraDamage,proto3" json:"extra_damage,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	PartX         int32                  `protobuf:"varint,6,opt,name=part_x,json=partX,proto3" json:"part_x,omitempty"`
	PartY         int32                  `protobuf:"varint,7,opt,name=part_y,json=partY,proto3" json:"part_y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TalentTriggerEvent) Reset() {
	*x = TalentTriggerEvent{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalentTriggerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentTriggerEvent) ProtoMessage() {}

func (x *TalentTriggerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentTriggerEvent.ProtoReflect.Descriptor instead.
func (*TalentTriggerEvent) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{19}
}

func (x *TalentTriggerEvent) GetTalentId() string {
	if x != nil {
		return x.TalentId
	}
	return ""
}

func (x *TalentTriggerEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TalentTriggerEvent) GetEffectType() string {
	if x != nil {
		return x.EffectType
	}
	return ""
}

func (x *TalentTriggerEvent) GetExtraDamage() int64 {
	if x != nil {
		return x.ExtraDamage
	}
	return 0
}

func (x *TalentTriggerEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TalentTriggerEvent) GetPartX() int32 {
	if x != nil {
		return x.PartX
	}
	return 0
}

func (x *TalentTriggerEvent) GetPartY() int32 {
	if x != nil {
		return x.PartY
	}
	return 0
}

type BossPartStateDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Damage        int64                  `protobuf:"varint,3,opt,name=damage,proto3" json:"damage,omitempty"`
	BeforeHp      int64                  `protobuf:"varint,4,opt,name=before_hp,json=beforeHp,proto3" json:"before_hp,omitempty"`
	AfterHp       int64                  `protobuf:"varint,5,opt,name=after_hp,json=afterHp,proto3" json:"after_hp,omitempty"`
	PartType      string                 `protobuf:"bytes,6,opt,name=part_type,json=partType,proto3" json:"part_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BossPartStateDelta) Reset() {
	*x = BossPartStateDelta{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BossPartStateDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BossPartStateDelta) ProtoMessage() {}

func (x *BossPartStateDelta) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BossPartStateDelta.ProtoReflect.Descriptor instead.
func (*BossPartStateDelta) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{20}
}

func (x *BossPartStateDelta) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BossPartStateDelta) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BossPartStateDelta) GetDamage() int64 {
	if x != nil {
		return x.Damage
	}
	return 0
}

func (x *BossPartStateDelta) GetBeforeHp() int64 {
	if x != nil {
		return x.BeforeHp
	}
	return 0
}

func (x *BossPartStateDelta) GetAfterHp() int64 {
	if x != nil {
		return x.AfterHp
	}
	return 0
}

func (x *BossPartStateDelta) GetPartType() string {
	if x != nil {
		return x.PartType
	}
	return ""
}

type TalentBleedState struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StartedAtMs    int64                  `protobuf:"varint,1,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	NextTickAtMs   int64                  `protobuf:"varint,2,opt,name=next_tick_at_ms,json=nextTickAtMs,proto3" json:"next_tick_at_ms,omitempty"`
	EndsAtMs       int64                  `protobuf:"varint,3,opt,name=ends_at_ms,json=endsAtMs,proto3" json:"ends_at_ms,omitempty"`
	DurationMs     int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TickIntervalMs int64                  `protobuf:"varint,5,opt,name=tick_interval_ms,json=tickIntervalMs,proto3" json:"tick_interval_ms,omitempty"`
	TotalTicks     int64                  `protobuf:"varint,6,opt,name=total_ticks,json=totalTicks,proto3" json:"total_ticks,omitempty"`
	AppliedTicks   int64                  `protobuf:"varint,7,opt,name=applied_ticks,json=appliedTicks,proto3" json:"applied_ticks,omitempty"`
	TotalDamage    int64                  `protobuf:"varint,8,opt,name=total_damage,json=totalDamage,proto3" json:"total_damage,omitempty"`
	AppliedDamage  int64                  `protobuf:"varint,9,opt,name=applied_damage,json=appliedDamage,proto3" json:"applied_damage,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TalentBleedState) Reset() {
	*x = TalentBleedState{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalentBleedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentBleedState) ProtoMessage() {}

func (x *TalentBleedState) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentBleedState.ProtoReflect.Descriptor instead.
func (*TalentBleedState) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{21}
}

func (x *TalentBleedState) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *TalentBleedState) GetNextTickAtMs() int64 {
	if x != nil {
		return x.NextTickAtMs
	}
	return 0
}

func (x *TalentBleedState) GetEndsAtMs() int64 {
	if x != nil {
		return x.EndsAtMs
	}
	return 0
}

func (x *TalentBleedState) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *TalentBleedState) GetTickIntervalMs() int64 {
	if x != nil {
		return x.TickIntervalMs
	}
	return 0
}

func (x *TalentBleedState) GetTotalTicks() int64 {
	if x != nil {
		return x.TotalTicks
	}
	return 0
}

func (x *TalentBleedState) GetAppliedTicks() int64 {
	if x != nil {
		return x.AppliedTicks
	}
	return 0
}

func (x *TalentBleedState) GetTotalDamage() int64 {
	if x != nil {
		return x.TotalDamage
	}
	return 0
}

func (x *TalentBleedState) GetAppliedDamage() int64 {
	if x != nil {
		return x.AppliedDamage
	}
	return 0
}

type TalentCombatState struct {
	state                   protoimpl.MessageState       `protogen:"open.v1"`
	OmenStacks              int32                        `protobuf:"varint,1,opt,name=omen_stacks,json=omenStacks,proto3" json:"omen_stacks,omitempty"`
	Bleeds                  map[string]*TalentBleedState `protobuf:"bytes,2,rep,name=bleeds,proto3" json:"bleeds,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	CollapseParts           []int32                      `protobuf:"varint,3,rep,packed,name=collapse_parts,json=collapseParts,proto3" json:"collapse_parts,omitempty"`
	CollapseEndsAt          int64                        `protobuf:"varint,4,opt,name=collapse_ends_at,json=collapseEndsAt,proto3" json:"collapse_ends_at,omitempty"`
	CollapseDuration        int64                        `protobuf:"varint,5,opt,name=collapse_duration,json=collapseDuration,proto3" json:"collapse_duration,omitempty"`
	DoomMarks               []int32                      `protobuf:"varint,6,rep,packed,name=doom_marks,json=doomMarks,proto3" json:"doom_marks,omitempty"`
	HasTriggeredDoom        bool                         `protobuf:"varint,7,opt,name=has_triggered_doom,json=hasTriggeredDoom,proto3" json:"has_triggered_doom,omitempty"`
	DoomMarkCumDamage       map[string]int64             `protobuf:"bytes,8,rep,name=doom_mark_cum_damage,json=doomMarkCumDamage,proto3" json:"doom_mark_cum_damage,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SilverStormRemaining    int32                        `protobuf:"varint,9,opt,name=silver_storm_remaining,json=silverStormRemaining,proto3" json:"silver_storm_remaining,omitempty"`
	SilverStormEndsAt       int64                        `protobuf:"varint,10,opt,name=silver_storm_ends_at,json=silverStormEndsAt,proto3" json:"silver_storm_ends_at,omitempty"`
	SilverStormActive       bool                         `protobuf:"varint,11,opt,name=silver_storm_active,json=silverStormActive,proto3" json:"silver_storm_active,omitempty"`
	AutoStrikeTargetPart    string                       `protobuf:"bytes,12,opt,name=auto_strike_target_part,json=autoStrikeTargetPart,proto3" json:"auto_strike_target_part,omitempty"`
	AutoStrikeComboCount    int64                        `protobuf:"varint,13,opt,name=auto_strike_combo_count,json=autoStrikeComboCount,proto3" json:"auto_strike_combo_count,omitempty"`
	AutoStrikeExpiresAt     int64                        `protobuf:"varint,14,opt,name=auto_strike_expires_at,json=autoStrikeExpiresAt,proto3" json:"auto_strike_expires_at,omitempty"`
	LastFinalCutAt          int64                        `protobuf:"varint,15,opt,name=last_final_cut_at,json=lastFinalCutAt,proto3" json:"last_final_cut_at,omitempty"`
	JudgmentDayUsed         map[string]int64             `protobuf:"bytes,16,rep,name=judgment_day_used,json=judgmentDayUsed,proto3" json:"judgment_day_used,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	JudgmentDayCooldownSec  int64                        `protobuf:"varint,17,opt,name=judgment_day_cooldown_sec,json=judgmentDayCooldownSec,proto3" json:"judgment_day_cooldown_sec,omitempty"`
	PartHeavyClickCount     map[string]int64             `protobuf:"bytes,18,rep,name=part_heavy_click_count,json=partHeavyClickCount,proto3" json:"part_heavy_click_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PartJudgmentDayCount    map[string]int64             `protobuf:"bytes,19,rep,name=part_judgment_day_count,json=partJudgmentDayCount,proto3" json:"part_judgment_day_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PartRetainedClicks      map[string]int64             `protobuf:"bytes,20,rep,name=part_retained_clicks,json=partRetainedClicks,proto3" json:"part_retained_clicks,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	PartStormComboCount     map[string]int64             `protobuf:"bytes,21,rep,name=part_storm_combo_count,json=partStormComboCount,proto3" json:"part_storm_combo_count,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkinnerParts            map[string]int64             `protobuf:"bytes,22,rep,name=skinner_parts,json=skinnerParts,proto3" json:"skinner_parts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkinnerDurationByPart   map[string]int64             `protobuf:"bytes,23,rep,name=skinner_duration_by_part,json=skinnerDurationByPart,proto3" json:"skinner_duration_by_part,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	SkinnerCooldownEndsAt   int64                        `protobuf:"varint,24,opt,name=skinner_cooldown_ends_at,json=skinnerCooldownEndsAt,proto3" json:"skinner_cooldown_ends_at,omitempty"`
	SkinnerCooldownDuration int64                        `protobuf:"varint,25,opt,name=skinner_cooldown_duration,json=skinnerCooldownDuration,proto3" json:"skinner_cooldown_duration,omitempty"`
	NormalTriggerCount      int64                        `protobuf:"varint,26,opt,name=normal_trigger_count,json=normalTriggerCount,proto3" json:"normal_trigger_count,omitempty"`
	ArmorTriggerCount       int64                        `protobuf:"varint,27,opt,name=armor_trigger_count,json=armorTriggerCount,proto3" json:"armor_trigger_count,omitempty"`
	JudgmentDayTriggerCount int64                        `protobuf:"varint,28,opt,name=judgment_day_trigger_count,json=judgmentDayTriggerCount,proto3" json:"judgment_day_trigger_count,omitempty"`
	AutoStrikeTriggerCount  int64                        `protobuf:"varint,29,opt,name=auto_strike_trigger_count,json=autoStrikeTriggerCount,proto3" json:"auto_strike_trigger_count,omitempty"`
	AutoStrikeWindowSec     int64                        `protobuf:"varint,30,opt,name=auto_strike_window_sec,json=autoStrikeWindowSec,proto3" json:"auto_strike_window_sec,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TalentCombatState) Reset() {
	*x = TalentCombatState{}
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TalentCombatState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentCombatState) ProtoMessage() {}

func (x *TalentCombatState) ProtoReflect() protoreflect.Message {
	mi := &file_backend_internal_realtimepb_realtime_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentCombatState.ProtoReflect.Descriptor instead.
func (*TalentCombatState) Descriptor() ([]byte, []int) {
	return file_backend_internal_realtimepb_realtime_proto_rawDescGZIP(), []int{22}
}

func (x *TalentCombatState) GetOmenStacks() int32 {
	if x != nil {
		return x.OmenStacks
	}
	return 0
}

func (x *TalentCombatState) GetBleeds() map[string]*TalentBleedState {
	if x != nil {
		return x.Bleeds
	}
	return nil
}

func (x *TalentCombatState) GetCollapseParts() []int32 {
	if x != nil {
		return x.CollapseParts
	}
	return nil
}

func (x *TalentCombatState) GetCollapseEndsAt() int64 {
	if x != nil {
		return x.CollapseEndsAt
	}
	return 0
}

func (x *TalentCombatState) GetCollapseDuration() int64 {
	if x != nil {
		return x.CollapseDuration
	}
	return 0
}

func (x *TalentCombatState) GetDoomMarks() []int32 {
	if x != nil {
		return x.DoomMarks
	}
	return nil
}

func (x *TalentCombatState) GetHasTriggeredDoom() bool {
	if x != nil {
		return x.HasTriggeredDoom
	}
	return false
}

func (x *TalentCombatState) GetDoomMarkCumDamage() map[string]int64 {
	if x != nil {
		return x.DoomMarkCumDamage
	}
	return nil
}

func (x *TalentCombatState) GetSilverStormRemaining() int32 {
	if x != nil {
		return x.SilverStormRemaining
	}
	return 0
}

func (x *TalentCombatState) GetSilverStormEndsAt() int64 {
	if x != nil {
		return x.SilverStormEndsAt
	}
	return 0
}

func (x *TalentCombatState) GetSilverStormActive() bool {
	if x != nil {
		return x.SilverStormActive
	}
	return false
}

func (x *TalentCombatState) GetAutoStrikeTargetPart() string {
	if x != nil {
		return x.AutoStrikeTargetPart
	}
	return ""
}

func (x *TalentCombatState) GetAutoStrikeComboCount() int64 {
	if x != nil {
		return x.AutoStrikeComboCount
	}
	return 0
}

func (x *TalentCombatState) GetAutoStrikeExpiresAt() int64 {
	if x != nil {
		return x.AutoStrikeExpiresAt
	}
	return 0
}

func (x *TalentCombatState) GetLastFinalCutAt() int64 {
	if x != nil {
		return x.LastFinalCutAt
	}
	return 0
}

func (x *TalentCombatState) GetJudgmentDayUsed() map[string]int64 {
	if x != nil {
		return x.JudgmentDayUsed
	}
	return nil
}

func (x *TalentCombatState) GetJudgmentDayCooldownSec() int64 {
	if x != nil {
		return x.JudgmentDayCooldownSec
	}
	return 0
}

func (x *TalentCombatState) GetPartHeavyClickCount() map[string]int64 {
	if x != nil {
		return x.PartHeavyClickCount
	}
	return nil
}

func (x *TalentCombatState) GetPartJudgmentDayCount() map[string]int64 {
	if x != nil {
		return x.PartJudgmentDayCount
	}
	return nil
}

func (x *TalentCombatState) GetPartRetainedClicks() map[string]int64 {
	if x != nil {
		return x.PartRetainedClicks
	}
	return nil
}

func (x *TalentCombatState) GetPartStormComboCount() map[string]int64 {
	if x != nil {
		return x.PartStormComboCount
	}
	return nil
}

func (x *TalentCombatState) GetSkinnerParts() map[string]int64 {
	if x != nil {
		return x.SkinnerParts
	}
	return nil
}

func (x *TalentCombatState) GetSkinnerDurationByPart() map[string]int64 {
	if x != nil {
		return x.SkinnerDurationByPart
	}
	return nil
}

func (x *TalentCombatState) GetSkinnerCooldownEndsAt() int64 {
	if x != nil {
		return x.SkinnerCooldownEndsAt
	}
	return 0
}

func (x *TalentCombatState) GetSkinnerCooldownDuration() int64 {
	if x != nil {
		return x.SkinnerCooldownDuration
	}
	return 0
}

func (x *TalentCombatState) GetNormalTriggerCount() int64 {
	if x != nil {
		return x.NormalTriggerCount
	}
	return 0
}

func (x *TalentCombatState) GetArmorTriggerCount() int64 {
	if x != nil {
		return x.ArmorTriggerCount
	}
	return 0
}

func (x *TalentCombatState) GetJudgmentDayTriggerCount() int64 {
	if x != nil {
		return x.JudgmentDayTriggerCount
	}
	return 0
}

func (x *TalentCombatState) GetAutoStrikeTriggerCount() int64 {
	if x != nil {
		return x.AutoStrikeTriggerCount
	}
	return 0
}

func (x *TalentCombatState) GetAutoStrikeWindowSec() int64 {
	if x != nil {
		return x.AutoStrikeWindowSec
	}
	return 0
}

var File_backend_internal_realtimepb_realtime_proto protoreflect.FileDescriptor

const file_backend_internal_realtimepb_realtime_proto_rawDesc = "" +
	"\n" +
	"*backend/internal/realtimepb/realtime.proto\x12\brealtime\"C\n" +
	"\fClickRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x1f\n" +
	"\vcombo_count\x18\x02 \x01(\x03R\n" +
	"comboCount\"\x9a\x04\n" +
	"\bClickAck\x12\x14\n" +
	"\x05delta\x18\x01 \x01(\x03R\x05delta\x12\x1a\n" +
	"\bcritical\x18\x02 \x01(\bR\bcritical\x12\x1f\n" +
	"\vboss_damage\x18\x03 \x01(\x03R\n" +
	"bossDamage\x12$\n" +
	"\x0emy_boss_damage\x18\x04 \x01(\x03R\fmyBossDamage\x124\n" +
	"\x16boss_leaderboard_count\x18\x05 \x01(\x05R\x14bossLeaderboardCount\x12\x1f\n" +
	"\vdamage_type\x18\x06 \x01(\tR\n" +
	"damageType\x12A\n" +
	"\rtalent_events\x18\a \x03(\v2\x1c.realtime.TalentTriggerEventR\ftalentEvents\x12H\n" +
	"\x11part_state_deltas\x18\b \x03(\v2\x1c.realtime.BossPartStateDeltaR\x0fpartStateDeltas\x12K\n" +
	"\x13talent_combat_state\x18\t \x01(\v2\x1b.realtime.TalentCombatStateR\x11talentCombatState\x127\n" +
	"\n" +
	"user_delta\x18\n" +
	" \x01(\v2\x18.realtime.UserDeltaPatchR\tuserDelta\x12+\n" +
	"\x06button\x18\v \x01(\v2\x13.realtime.ButtonRefR\x06button\"a\n" +
	"\x0eUserDeltaPatch\x12\x12\n" +
	"\x04gold\x18\x01 \x01(\x03R\x04gold\x12\x16\n" +
	"\x06stones\x18\x02 \x01(\x03R\x06stones\x12#\n" +
	"\rtalent_points\x18\x03 \x01(\x03R\ftalentPoints\"\x1d\n" +
	"\tButtonRef\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"\xa7\x02\n" +
	"\vPublicDelta\x12\x1f\n" +
	"\vtotal_votes\x18\x01 \x01(\x03R\n" +
	"totalVotes\x12<\n" +
	"\vleaderboard\x18\x02 \x03(\v2\x1a.realtime.LeaderboardEntryR\vleaderboard\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\"\n" +
	"\x04boss\x18\x04 \x01(\v2\x0e.realtime.BossR\x04boss\x12I\n" +
	"\x10boss_leaderboard\x18\x05 \x03(\v2\x1e.realtime.BossLeaderboardEntryR\x0fbossLeaderboard\x121\n" +
	"\x14announcement_version\x18\x06 \x01(\tR\x13announcementVersion\"\xc8\x01\n" +
	"\n" +
	"PublicMeta\x12<\n" +
	"\vleaderboard\x18\x01 \x03(\v2\x1a.realtime.LeaderboardEntryR\vleaderboard\x12I\n" +
	"\x10boss_leaderboard\x18\x02 \x03(\v2\x1e.realtime.BossLeaderboardEntryR\x0fbossLeaderboard\x121\n" +
	"\x14announcement_version\x18\x03 \x01(\tR\x13announcementVersion\"\x9e\x04\n" +
	"\bRoomInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x18\n" +
	"\acurrent\x18\x03 \x01(\bR\acurrent\x12\x1a\n" +
	"\bjoinable\x18\x04 \x01(\bR\bjoinable\x12!\n" +
	"\fonline_count\x18\x05 \x01(\x05R\vonlineCount\x12#\n" +
	"\rcycle_enabled\x18\x06 \x01(\bR\fcycleEnabled\x12\x19\n" +
	"\bqueue_id\x18\a \x01(\tR\aqueueId\x12&\n" +
	"\x0fcurrent_boss_id\x18\b \x01(\tR\rcurrentBossId\x12*\n" +
	"\x11current_boss_name\x18\t \x01(\tR\x0fcurrentBossName\x12.\n" +
	"\x13current_boss_status\x18\n" +
	" \x01(\tR\x11currentBossStatus\x12&\n" +
	"\x0fcurrent_boss_hp\x18\v \x01(\x03R\rcurrentBossHp\x12-\n" +
	"\x13current_boss_max_hp\x18\f \x01(\x03R\x10currentBossMaxHp\x12-\n" +
	"\x13current_boss_avg_hp\x18\r \x01(\x03R\x10currentBossAvgHp\x12<\n" +
	"\x1acooldown_remaining_seconds\x18\x0e \x01(\x03R\x18cooldownRemainingSeconds\"\xa8\x01\n" +
	"\tRoomState\x12&\n" +
	"\x0fcurrent_room_id\x18\x01 \x01(\tR\rcurrentRoomId\x12I\n" +
	"!switch_cooldown_remaining_seconds\x18\x02 \x01(\x03R\x1eswitchCooldownRemainingSeconds\x12(\n" +
	"\x05rooms\x18\x03 \x03(\v2\x12.realtime.RoomInfoR\x05rooms\"\xfb\x05\n" +
	"\tUserDelta\x122\n" +
	"\n" +
	"user_stats\x18\x01 \x01(\v2\x13.realtime.UserStatsR\tuserStats\x12;\n" +
	"\rmy_boss_stats\x18\x02 \x01(\v2\x17.realtime.BossUserStatsR\vmyBossStats\x12\"\n" +
	"\rmy_boss_kills\x18\x03 \x01(\x03R\vmyBossKills\x12(\n" +
	"\x10total_boss_kills\x18\x04 \x01(\x03R\x0etotalBossKills\x12\x17\n" +
	"\aroom_id\x18\x05 \x01(\tR\x06roomId\x12+\n" +
	"\aloadout\x18\x06 \x01(\v2\x11.realtime.LoadoutR\aloadout\x128\n" +
	"\fcombat_stats\x18\a \x01(\v2\x15.realtime.CombatStatsR\vcombatStats\x12\x12\n" +
	"\x04gold\x18\b \x01(\x03R\x04gold\x12\x16\n" +
	"\x06stones\x18\t \x01(\x03R\x06stones\x12#\n" +
	"\rtalent_points\x18\n" +
	" \x01(\x03R\ftalentPoints\x127\n" +
	"\x0erecent_rewards\x18\v \x03(\v2\x10.realtime.RewardR\rrecentRewards\x12A\n" +
	"\rtalent_events\x18\f \x03(\v2\x1c.realtime.TalentTriggerEventR\ftalentEvents\x12K\n" +
	"\x13talent_combat_state\x18\r \x01(\v2\x1b.realtime.TalentCombatStateR\x11talentCombatState\x12@\n" +
	"\x1dequipped_battle_click_skin_id\x18\x0e \x01(\tR\x19equippedBattleClickSkinId\x12S\n" +
	"'equipped_battle_click_cursor_image_path\x18\x0f \x01(\tR\"equippedBattleClickCursorImagePath\"H\n" +
	"\tUserStats\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1f\n" +
	"\vclick_count\x18\x02 \x01(\x03R\n" +
	"clickCount\"c\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1f\n" +
	"\vclick_count\x18\x03 \x01(\x03R\n" +
	"clickCount\"\xde\x01\n" +
	"\bBossPart\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12\x1d\n" +
	"\n" +
	"image_path\x18\x05 \x01(\tR\timagePath\x12\x15\n" +
	"\x06max_hp\x18\x06 \x01(\x03R\x05maxHp\x12\x1d\n" +
	"\n" +
	"current_hp\x18\a \x01(\x03R\tcurrentHp\x12\x14\n" +
	"\x05armor\x18\b \x01(\x03R\x05armor\x12\x14\n" +
	"\x05alive\x18\t \x01(\bR\x05alive\"\xb0\x03\n" +
	"\x04Boss\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\tR\n" +
	"templateId\x12\x17\n" +
	"\aroom_id\x18\x03 \x01(\tR\x06roomId\x12\x19\n" +
	"\bqueue_id\x18\x04 \x01(\tR\aqueueId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x15\n" +
	"\x06max_hp\x18\a \x01(\x03R\x05maxHp\x12\x1d\n" +
	"\n" +
	"current_hp\x18\b \x01(\x03R\tcurrentHp\x12 \n" +
	"\fgold_on_kill\x18\t \x01(\x03R\n" +
	"goldOnKill\x12\"\n" +
	"\rstone_on_kill\x18\n" +
	" \x01(\x03R\vstoneOnKill\x121\n" +
	"\x15talent_points_on_kill\x18\v \x01(\x03R\x12talentPointsOnKill\x12(\n" +
	"\x05parts\x18\f \x03(\v2\x12.realtime.BossPartR\x05parts\x12\x1d\n" +
	"\n" +
	"started_at\x18\r \x01(\x03R\tstartedAt\x12\x1f\n" +
	"\vdefeated_at\x18\x0e \x01(\x03R\n" +
	"defeatedAt\"^\n" +
	"\x14BossLeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x05R\x04rank\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x03R\x06damage\"W\n" +
	"\rBossUserStats\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x03R\x06damage\x12\x12\n" +
	"\x04rank\x18\x03 \x01(\x05R\x04rank\"\x8d\x05\n" +
	"\rInventoryItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04slot\x18\x04 \x01(\tR\x04slot\x12\x16\n" +
	"\x06rarity\x18\x05 \x01(\tR\x06rarity\x12\x1d\n" +
	"\n" +
	"image_path\x18\x06 \x01(\tR\timagePath\x12\x1b\n" +
	"\timage_alt\x18\a \x01(\tR\bimageAlt\x12\x1a\n" +
	"\bquantity\x18\b \x01(\x03R\bquantity\x12\x1a\n" +
	"\bequipped\x18\t \x01(\bR\bequipped\x12#\n" +
	"\renhance_level\x18\n" +
	" \x01(\x05R\fenhanceLevel\x12\x14\n" +
	"\x05bound\x18\v \x01(\bR\x05bound\x12\x16\n" +
	"\x06locked\x18\f \x01(\bR\x06locked\x12!\n" +
	"\fattack_power\x18\r \x01(\x03R\vattackPower\x12*\n" +
	"\x11armor_pen_percent\x18\x0e \x01(\x01R\x0farmorPenPercent\x12\x1b\n" +
	"\tcrit_rate\x18\x0f \x01(\x01R\bcritRate\x124\n" +
	"\x16crit_damage_multiplier\x18\x10 \x01(\x01R\x14critDamageMultiplier\x121\n" +
	"\x15part_type_damage_soft\x18\x11 \x01(\x01R\x12partTypeDamageSoft\x123\n" +
	"\x16part_type_damage_heavy\x18\x12 \x01(\x01R\x13partTypeDamageHeavy\x121\n" +
	"\x15part_type_damage_weak\x18\x13 \x01(\x01R\x12partTypeDamageWeak\"\xaf\x02\n" +
	"\aLoadout\x12/\n" +
	"\x06weapon\x18\x01 \x01(\v2\x17.realtime.InventoryItemR\x06weapon\x12/\n" +
	"\x06helmet\x18\x02 \x01(\v2\x17.realtime.InventoryItemR\x06helmet\x12-\n" +
	"\x05chest\x18\x03 \x01(\v2\x17.realtime.InventoryItemR\x05chest\x12/\n" +
	"\x06gloves\x18\x04 \x01(\v2\x17.realtime.InventoryItemR\x06gloves\x12+\n" +
	"\x04legs\x18\x05 \x01(\v2\x17.realtime.InventoryItemR\x04legs\x125\n" +
	"\taccessory\x18\x06 \x01(\v2\x17.realtime.InventoryItemR\taccessory\"\x9f\x05\n" +
	"\vCombatStats\x12/\n" +
	"\x13effective_increment\x18\x01 \x01(\x03R\x12effectiveIncrement\x12#\n" +
	"\rnormal_damage\x18\x02 \x01(\x03R\fnormalDamage\x126\n" +
	"\x17critical_chance_percent\x18\x03 \x01(\x01R\x15criticalChancePercent\x12'\n" +
	"\x0fcritical_damage\x18\x04 \x01(\x03R\x0ecriticalDamage\x12!\n" +
	"\fattack_power\x18\x05 \x01(\x03R\vattackPower\x12*\n" +
	"\x11armor_pen_percent\x18\x06 \x01(\x01R\x0farmorPenPercent\x124\n" +
	"\x16crit_damage_multiplier\x18\a \x01(\x01R\x14critDamageMultiplier\x12,\n" +
	"\x12all_damage_amplify\x18\b \x01(\x01R\x10allDamageAmplify\x121\n" +
	"\x15part_type_damage_soft\x18\t \x01(\x01R\x12partTypeDamageSoft\x123\n" +
	"\x16part_type_damage_heavy\x18\n" +
	" \x01(\x01R\x13partTypeDamageHeavy\x121\n" +
	"\x15part_type_damage_weak\x18\v \x01(\x01R\x12partTypeDamageWeak\x125\n" +
	"\x17per_part_damage_percent\x18\f \x01(\x01R\x14perPartDamagePercent\x12*\n" +
	"\x11low_hp_multiplier\x18\r \x01(\x01R\x0flowHpMultiplier\x12(\n" +
	"\x10low_hp_threshold\x18\x0e \x01(\x01R\x0elowHpThreshold\"\x93\x01\n" +
	"\x06Reward\x12\x17\n" +
	"\aboss_id\x18\x01 \x01(\tR\x06bossId\x12\x1b\n" +
	"\tboss_name\x18\x02 \x01(\tR\bbossName\x12\x17\n" +
	"\aitem_id\x18\x03 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x04 \x01(\tR\bitemName\x12\x1d\n" +
	"\n" +
	"granted_at\x18\x05 \x01(\x03R\tgrantedAt\"\xd1\x01\n" +
	"\x12TalentTriggerEvent\x12\x1b\n" +
	"\ttalent_id\x18\x01 \x01(\tR\btalentId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\veffect_type\x18\x03 \x01(\tR\n" +
	"effectType\x12!\n" +
	"\fextra_damage\x18\x04 \x01(\x03R\vextraDamage\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\x12\x15\n" +
	"\x06part_x\x18\x06 \x01(\x05R\x05partX\x12\x15\n" +
	"\x06part_y\x18\a \x01(\x05R\x05partY\"\x9d\x01\n" +
	"\x12BossPartStateDelta\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x16\n" +
	"\x06damage\x18\x03 \x01(\x03R\x06damage\x12\x1b\n" +
	"\tbefore_hp\x18\x04 \x01(\x03R\bbeforeHp\x12\x19\n" +
	"\bafter_hp\x18\x05 \x01(\x03R\aafterHp\x12\x1b\n" +
	"\tpart_type\x18\x06 \x01(\tR\bpartType\"\xd6\x02\n" +
	"\x10TalentBleedState\x12\"\n" +
	"\rstarted_at_ms\x18\x01 \x01(\x03R\vstartedAtMs\x12%\n" +
	"\x0fnext_tick_at_ms\x18\x02 \x01(\x03R\fnextTickAtMs\x12\x1c\n" +
	"\n" +
	"ends_at_ms\x18\x03 \x01(\x03R\bendsAtMs\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12(\n" +
	"\x10tick_interval_ms\x18\x05 \x01(\x03R\x0etickIntervalMs\x12\x1f\n" +
	"\vtotal_ticks\x18\x06 \x01(\x03R\n" +
	"totalTicks\x12#\n" +
	"\rapplied_ticks\x18\a \x01(\x03R\fappliedTicks\x12!\n" +
	"\ftotal_damage\x18\b \x01(\x03R\vtotalDamage\x12%\n" +
	"\x0eapplied_damage\x18\t \x01(\x03R\rappliedDamage\"\xa3\x14\n" +
	"\x11TalentCombatState\x12\x1f\n" +
	"\vomen_stacks\x18\x01 \x01(\x05R\n" +
	"omenStacks\x12?\n" +
	"\x06bleeds\x18\x02 \x03(\v2'.realtime.TalentCombatState.BleedsEntryR\x06bleeds\x12%\n" +
	"\x0ecollapse_parts\x18\x03 \x03(\x05R\rcollapseParts\x12(\n" +
	"\x10collapse_ends_at\x18\x04 \x01(\x03R\x0ecollapseEndsAt\x12+\n" +
	"\x11collapse_duration\x18\x05 \x01(\x03R\x10collapseDuration\x12\x1d\n" +
	"\n" +
	"doom_marks\x18\x06 \x03(\x05R\tdoomMarks\x12,\n" +
	"\x12has_triggered_doom\x18\a \x01(\bR\x10hasTriggeredDoom\x12c\n" +
	"\x14doom_mark_cum_damage\x18\b \x03(\v22.realtime.TalentCombatState.DoomMarkCumDamageEntryR\x11doomMarkCumDamage\x124\n" +
	"\x16silver_storm_remaining\x18\t \x01(\x05R\x14silverStormRemaining\x12/\n" +
	"\x14silver_storm_ends_at\x18\n" +
	" \x01(\x03R\x11silverStormEndsAt\x12.\n" +
	"\x13silver_storm_active\x18\v \x01(\bR\x11silverStormActive\x125\n" +
	"\x17auto_strike_target_part\x18\f \x01(\tR\x14autoStrikeTargetPart\x125\n" +
	"\x17auto_strike_combo_count\x18\r \x01(\x03R\x14autoStrikeComboCount\x123\n" +
	"\x16auto_strike_expires_at\x18\x0e \x01(\x03R\x13autoStrikeExpiresAt\x12)\n" +
	"\x11last_final_cut_at\x18\x0f \x01(\x03R\x0elastFinalCutAt\x12\\\n" +
	"\x11judgment_day_used\x18\x10 \x03(\v20.realtime.TalentCombatState.JudgmentDayUsedEntryR\x0fjudgmentDayUsed\x129\n" +
	"\x19judgment_day_cooldown_sec\x18\x11 \x01(\x03R\x16judgmentDayCooldownSec\x12i\n" +
	"\x16part_heavy_click_count\x18\x12 \x03(\v24.realtime.TalentCombatState.PartHeavyClickCountEntryR\x13partHeavyClickCount\x12l\n" +
	"\x17part_judgment_day_count\x18\x13 \x03(\v25.realtime.TalentCombatState.PartJudgmentDayCountEntryR\x14partJudgmentDayCount\x12e\n" +
	"\x14part_retained_clicks\x18\x14 \x03(\v23.realtime.TalentCombatState.PartRetainedClicksEntryR\x12partRetainedClicks\x12i\n" +
	"\x16part_storm_combo_count\x18\x15 \x03(\v24.realtime.TalentCombatState.PartStormComboCountEntryR\x13partStormComboCount\x12R\n" +
	"\rskinner_parts\x18\x16 \x03(\v2-.realtime.TalentCombatState.SkinnerPartsEntryR\fskinnerParts\x12o\n" +
	"\x18skinner_duration_by_part\x18\x17 \x03(\v26.realtime.TalentCombatState.SkinnerDurationByPartEntryR\x15skinnerDurationByPart\x127\n" +
	"\x18skinner_cooldown_ends_at\x18\x18 \x01(\x03R\x15skinnerCooldownEndsAt\x12:\n" +
	"\x19skinner_cooldown_duration\x18\x19 \x01(\x03R\x17skinnerCooldownDuration\x120\n" +
	"\x14normal_trigger_count\x18\x1a \x01(\x03R\x12normalTriggerCount\x12.\n" +
	"\x13armor_trigger_count\x18\x1b \x01(\x03R\x11armorTriggerCount\x12;\n" +
	"\x1ajudgment_day_trigger_count\x18\x1c \x01(\x03R\x17judgmentDayTriggerCount\x129\n" +
	"\x19auto_strike_trigger_count\x18\x1d \x01(\x03R\x16autoStrikeTriggerCount\x123\n" +
	"\x16auto_strike_window_sec\x18\x1e \x01(\x03R\x13autoStrikeWindowSec\x1aU\n" +
	"\vBleedsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.realtime.TalentBleedStateR\x05value:\x028\x01\x1aD\n" +
	"\x16DoomMarkCumDamageEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14JudgmentDayUsedEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aF\n" +
	"\x18PartHeavyClickCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aG\n" +
	"\x19PartJudgmentDayCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aE\n" +
	"\x17PartRetainedClicksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aF\n" +
	"\x18PartStormComboCountEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11SkinnerPartsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aH\n" +
	"\x1aSkinnerDurationByPartEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\x1aZ\x18long/internal/realtimepbb\x06proto3"

var (
	file_backend_internal_realtimepb_realtime_proto_rawDescOnce sync.Once
	file_backend_internal_realtimepb_realtime_proto_rawDescData []byte
)

func file_backend_internal_realtimepb_realtime_proto_rawDescGZIP() []byte {
	file_backend_internal_realtimepb_realtime_proto_rawDescOnce.Do(func() {
		file_backend_internal_realtimepb_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_internal_realtimepb_realtime_proto_rawDesc), len(file_backend_internal_realtimepb_realtime_proto_rawDesc)))
	})
	return file_backend_internal_realtimepb_realtime_proto_rawDescData
}

var file_backend_internal_realtimepb_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_backend_internal_realtimepb_realtime_proto_goTypes = []any{
	(*ClickRequest)(nil),         // 0: realtime.ClickRequest
	(*ClickAck)(nil),             // 1: realtime.ClickAck
	(*UserDeltaPatch)(nil),       // 2: realtime.UserDeltaPatch
	(*ButtonRef)(nil),            // 3: realtime.ButtonRef
	(*PublicDelta)(nil),          // 4: realtime.PublicDelta
	(*PublicMeta)(nil),           // 5: realtime.PublicMeta
	(*RoomInfo)(nil),             // 6: realtime.RoomInfo
	(*RoomState)(nil),            // 7: realtime.RoomState
	(*UserDelta)(nil),            // 8: realtime.UserDelta
	(*UserStats)(nil),            // 9: realtime.UserStats
	(*LeaderboardEntry)(nil),     // 10: realtime.LeaderboardEntry
	(*BossPart)(nil),             // 11: realtime.BossPart
	(*Boss)(nil),                 // 12: realtime.Boss
	(*BossLeaderboardEntry)(nil), // 13: realtime.BossLeaderboardEntry
	(*BossUserStats)(nil),        // 14: realtime.BossUserStats
	(*InventoryItem)(nil),        // 15: realtime.InventoryItem
	(*Loadout)(nil),              // 16: realtime.Loadout
	(*CombatStats)(nil),          // 17: realtime.CombatStats
	(*Reward)(nil),               // 18: realtime.Reward
	(*TalentTriggerEvent)(nil),   // 19: realtime.TalentTriggerEvent
	(*BossPartStateDelta)(nil),   // 20: realtime.BossPartStateDelta
	(*TalentBleedState)(nil),     // 21: realtime.TalentBleedState
	(*TalentCombatState)(nil),    // 22: realtime.TalentCombatState
	nil,                          // 23: realtime.TalentCombatState.BleedsEntry
	nil,                          // 24: realtime.TalentCombatState.DoomMarkCumDamageEntry
	nil,                          // 25: realtime.TalentCombatState.JudgmentDayUsedEntry
	nil,                          // 26: realtime.TalentCombatState.PartHeavyClickCountEntry
	nil,                          // 27: realtime.TalentCombatState.PartJudgmentDayCountEntry
	nil,                          // 28: realtime.TalentCombatState.PartRetainedClicksEntry
	nil,                          // 29: realtime.TalentCombatState.PartStormComboCountEntry
	nil,                          // 30: realtime.TalentCombatState.SkinnerPartsEntry
	nil,                          // 31: realtime.TalentCombatState.SkinnerDurationByPartEntry
}
var file_backend_internal_realtimepb_realtime_proto_depIdxs = []int32{
	19, // 0: realtime.ClickAck.talent_events:type_name -> realtime.TalentTriggerEvent
	20, // 1: realtime.ClickAck.part_state_deltas:type_name -> realtime.BossPartStateDelta
	22, // 2: realtime.ClickAck.talent_combat_state:type_name -> realtime.TalentCombatState
	2,  // 3: realtime.ClickAck.user_delta:type_name -> realtime.UserDeltaPatch
	3,  // 4: realtime.ClickAck.button:type_name -> realtime.ButtonRef
	10, // 5: realtime.PublicDelta.leaderboard:type_name -> realtime.LeaderboardEntry
	12, // 6: realtime.PublicDelta.boss:type_name -> realtime.Boss
	13, // 7: realtime.PublicDelta.boss_leaderboard:type_name -> realtime.BossLeaderboardEntry
	10, // 8: realtime.PublicMeta.leaderboard:type_name -> realtime.LeaderboardEntry
	13, // 9: realtime.PublicMeta.boss_leaderboard:type_name -> realtime.BossLeaderboardEntry
	6,  // 10: realtime.RoomState.rooms:type_name -> realtime.RoomInfo
	9,  // 11: realtime.UserDelta.user_stats:type_name -> realtime.UserStats
	14, // 12: realtime.UserDelta.my_boss_stats:type_name -> realtime.BossUserStats
	16, // 13: realtime.UserDelta.loadout:type_name -> realtime.Loadout
	17, // 14: realtime.UserDelta.combat_stats:type_name -> realtime.CombatStats
	18, // 15: realtime.UserDelta.recent_rewards:type_name -> realtime.Reward
	19, // 16: realtime.UserDelta.talent_events:type_name -> realtime.TalentTriggerEvent
	22, // 17: realtime.UserDelta.talent_combat_state:type_name -> realtime.TalentCombatState
	11, // 18: realtime.Boss.parts:type_name -> realtime.BossPart
	15, // 19: realtime.Loadout.weapon:type_name -> realtime.InventoryItem
	15, // 20: realtime.Loadout.helmet:type_name -> realtime.InventoryItem
	15, // 21: realtime.Loadout.chest:type_name -> realtime.InventoryItem
	15, // 22: realtime.Loadout.gloves:type_name -> realtime.InventoryItem
	15, // 23: realtime.Loadout.legs:type_name -> realtime.InventoryItem
	15, // 24: realtime.Loadout.accessory:type_name -> realtime.InventoryItem
	23, // 25: realtime.TalentCombatState.bleeds:type_name -> realtime.TalentCombatState.BleedsEntry
	24, // 26: realtime.TalentCombatState.doom_mark_cum_damage:type_name -> realtime.TalentCombatState.DoomMarkCumDamageEntry
	25, // 27: realtime.TalentCombatState.judgment_day_used:type_name -> realtime.TalentCombatState.JudgmentDayUsedEntry
	26, // 28: realtime.TalentCombatState.part_heavy_click_count:type_name -> realtime.TalentCombatState.PartHeavyClickCountEntry
	27, // 29: realtime.TalentCombatState.part_judgment_day_count:type_name -> realtime.TalentCombatState.PartJudgmentDayCountEntry
	28, // 30: realtime.TalentCombatState.part_retained_clicks:type_name -> realtime.TalentCombatState.PartRetainedClicksEntry
	29, // 31: realtime.TalentCombatState.part_storm_combo_count:type_name -> realtime.TalentCombatState.PartStormComboCountEntry
	30, // 32: realtime.TalentCombatState.skinner_parts:type_name -> realtime.TalentCombatState.SkinnerPartsEntry
	31, // 33: realtime.TalentCombatState.skinner_duration_by_part:type_name -> realtime.TalentCombatState.SkinnerDurationByPartEntry
	21, // 34: realtime.TalentCombatState.BleedsEntry.value:type_name -> realtime.TalentBleedState
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_backend_internal_realtimepb_realtime_proto_init() }
func file_backend_internal_realtimepb_realtime_proto_init() {
	if File_backend_internal_realtimepb_realtime_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_internal_realtimepb_realtime_proto_rawDesc), len(file_backend_internal_realtimepb_realtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_internal_realtimepb_realtime_proto_goTypes,
		DependencyIndexes: file_backend_internal_realtimepb_realtime_proto_depIdxs,
		MessageInfos:      file_backend_internal_realtimepb_realtime_proto_msgTypes,
	}.Build()
	File_backend_internal_realtimepb_realtime_proto = out.File
	file_backend_internal_realtimepb_realtime_proto_goTypes = nil
	file_backend_internal_realtimepb_realtime_proto_depIdxs = nil
}
