import {existsSync, readFileSync} from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

import {describe, expect, it} from 'vitest'

const currentDir = path.dirname(fileURLToPath(import.meta.url))
const battleSource = readFileSync(path.resolve(currentDir, './BattlePage.vue'), 'utf8')
const stateSource = readFileSync(path.resolve(currentDir, './publicPageState.js'), 'utf8')
const styleSource = readFileSync(path.resolve(currentDir, '../style.css'), 'utf8')
const docsPath = path.resolve(currentDir, '../../../docs/implementation/2026-04-29-伤害动画解析优先级.md')
const compactBattleSource = battleSource.replace(/\s+/g, ' ')
const compactStyleSource = styleSource.replace(/\s+/g, ' ')

describe('BattlePage 光标与伤害说明', () => {
    it('死兆改到左侧统一全局状态面板，并按 150 层显示进度', () => {
        expect(stateSource).toContain("kind: 'omen'")
        expect(stateSource).toContain('const omenStacks = Math.max(0, Number(talentVisualState.value?.omenStacks) || 0)')
        expect(stateSource).toContain('const omenCap = Math.max(1, Number(talentVisualState.value?.omenCap) || 150)')
        expect(stateSource).toContain("title: '死兆'")
        expect(stateSource).toContain("primary: `${omenStacks} / ${omenCap}`")
        expect(stateSource).toContain("hint: `${omenCap} 层自动触发终末血斩`")
        expect(battleSource).toContain('class="status-panel"')
        expect(battleSource).not.toContain('class="talent-omen-ring__svg"')
        expect(styleSource).toContain('background: linear-gradient(180deg, rgba(69, 10, 10, 0.94), rgba(127, 29, 29, 0.82));')
        expect(styleSource).toContain('border: 1px solid rgba(248, 113, 113, 0.28);')
        expect(styleSource).toContain('color: #fca5a5;')
        expect(styleSource).toContain('color: #fee2e2;')
    })

    it('Boss 网格已移除鼠标轨迹采样，只保留光标显示所需事件', () => {
        expect(battleSource).toContain("ref=\"bossGridRef\"")
        expect(battleSource).toContain('@pointerenter="handleBossGridPointerEnter"')
        expect(battleSource).toContain('@pointerleave="handleBossGridPointerLeave"')
        expect(battleSource).toContain('https://hai-world2.oss-cn-beijing.aliyuncs.com/effects/click-sword_basic.png')
        expect(battleSource).toContain(':src="bossSwordCursorUrl"')
        expect(battleSource).not.toContain('bossSwordCursorUrl.value')
        expect(battleSource).toContain('let bossCursorFrame = 0')
        expect(battleSource).toContain('let pendingBossCursorPoint = null')
        expect(battleSource).toContain('bossCursorFrame = requestAnimationFrame(() => {')
        expect(battleSource).toContain('swordCursor.style.transform = `translate(${x}px, ${y}px) translate(-50%, -50%)`')
        expect(battleSource).toContain('function measureBossGridRect() {')
        expect(battleSource).toContain('bossGridRect = grid.getBoundingClientRect()')
        expect(battleSource).not.toContain('const bossCursorX = ref(0)')
        expect(battleSource).not.toContain('const bossCursorY = ref(0)')
        expect(styleSource).toContain('.boss-part-grid-with-combo * {')
        expect(styleSource).toContain('cursor: none !important;')
        expect(styleSource).toContain('width: 72px;')
        expect(styleSource).toContain('height: 72px;')
        expect(styleSource).toContain('will-change: transform, opacity;')
        expect(styleSource).toContain('transition: opacity 0.08s ease-out;')
        expect(styleSource).toContain('.boss-sword-cursor__image {')
        expect(battleSource).toContain('@pointermove="handleBossGridPointerMove"')
        expect(battleSource).not.toContain('createMousePathTracker')
        expect(battleSource).not.toContain('mousePathTracker')
        expect(battleSource).not.toContain("document.addEventListener('pointermove'")
        expect(battleSource).not.toContain("document.addEventListener('pointerdown'")
        expect(battleSource).not.toContain("document.addEventListener('click'")
    })

    it('点击火花改为 body 粒子后，仍保持方块像素粒子而不是圆点发光', () => {
        expect(battleSource).toContain("arcane: {colors: ['#c4b5fd', '#7c3aed', '#22d3ee', '#a78bfa', '#38bdf8'], count: 10, gravity: 0.05}")
        expect(battleSource).toContain("if (cell.classList.contains('boss-part-cell--arcane')) return 'arcane'")
        expect(battleSource).toContain("boss-part-cell--arcane': zone?.type === 'arcane'")
        expect(battleSource).toContain("el.className = 'sword-spark'")
        expect(battleSource).toContain('document.body.appendChild(el)')
        expect(styleSource).toContain('.sword-spark {')
        expect(styleSource).toContain('position: fixed;')
        expect(styleSource).toContain('pointer-events: none;')
        expect(styleSource).toContain('z-index: 45;')
        expect(styleSource).toContain('.boss-part-cell--arcane {')
        expect(styleSource).toContain('.boss-part-info__item--arcane .boss-part-info__value {')
        expect(compactStyleSource).toContain('.sword-spark { position: fixed; left: 0; top: 0; pointer-events: none; z-index: 45; border-radius: 0; transform: translate(-50%, -50%); }')
    })

    it('奥核普通点击不再显示基础 -5，而是显示物理无效化', () => {
        expect(stateSource).toContain("part?.damageAffinity === 'magic_only'")
        expect(stateSource).toContain("return 'physicalInvalid'")
        expect(stateSource).toContain("physicalInvalid: {")
        expect(stateSource).toContain("label: '物理无效化'")
        expect(battleSource).toContain("v-if=\"burst.type === 'physicalInvalid'\"")
        expect(battleSource).not.toContain('基础 -5')
    })

    it('右侧伤害类型说明把重甲替换为真实伤害', () => {
        expect(battleSource).toContain('boss-right-legend__icon">⚡</span>')
        expect(compactBattleSource).toContain('boss-right-legend__item--true"><span class="boss-right-legend__icon">⚡</span>真实伤害</span>')
        expect(battleSource).not.toContain('boss-right-legend__item--true">重甲</span>')
        expect(stateSource).toContain("label: '⚡'")
        expect(stateSource).toContain("heavy: {")
        expect(stateSource).toContain("return 'heavy'")
        expect(stateSource).toContain("talentVisualState.value.collapsePartKeys.includes(`${part.x}-${part.y}`)")
        expect(stateSource).toContain("return 'trueDamage'")
        expect(styleSource).toContain('.boss-right-legend__item--true {')
        expect(styleSource).toContain('color: #c084fc;')
        expect(styleSource).toContain('border-color: rgba(192, 132, 252, 0.3);')
        expect(styleSource).toContain('.boss-zone-button__damage-burst--heavy {')
        expect(styleSource).toContain('.boss-zone-button__damage-burst--trueDamage {')
        expect(styleSource).toContain('font-size: 1.1em;')
    })

    it('削血和终结的实际伤害弹字单独缩小，不影响其他伤害类型', () => {
        expect(styleSource).toContain('.boss-zone-button__damage-burst--doomsday {')
        expect(styleSource).toContain('font-size: clamp(2.1rem, 4.4vw, 3.8rem);')
        expect(styleSource).toContain('.boss-zone-button__damage-burst--judgement {')
        expect(styleSource).toContain('font-size: clamp(2.4rem, 5vw, 4.4rem);')
        expect(stateSource).toContain('scale: 2.15,')
        expect(stateSource).toContain('scale: 2.75,')
    })

    it('出血结算通过用户态事件触发独立小字，并且不再走主伤害 burst 截断队列', () => {
        expect(styleSource).toContain('.boss-zone-button__damage-burst--bleed {')
        expect(styleSource).toContain('font-size: 0.86em;')
        expect(stateSource).toContain('function triggerTalentEventDamageBursts(events) {')
        expect(stateSource).toContain("const effectType = String(event.effectType || '')")
        expect(stateSource).toContain("if (effectType === 'bleed') {")
        expect(stateSource).toContain("if (effectType === 'magic_burst' || effectType === 'magic_starfall') {")
        expect(stateSource).toContain('function triggerBleedBurst(partKey, payload = {}) {')
        expect(stateSource).toContain('const currentBursts = bleedBursts.value[normalizedKey] || []')
        expect(stateSource).toContain('bleedBursts,')
        expect(stateSource).toContain('bleedTriggerFeed,')
        expect(stateSource).toContain('ttl: 280,')
        expect(stateSource).toContain("if (variant === 'bleed') {")
        expect(stateSource).toContain('function appendBleedTriggerEvents(events) {')
        expect(stateSource).toContain('bleedTriggerFeed.value = [')
        expect(stateSource).toContain('function appendBleedTriggerEvents(events) {')
        expect(stateSource).toContain('bleedTriggerFeed.value = [')
        expect(stateSource).toContain("const PERSISTENT_TALENT_EFFECT_TYPES = new Set(['magic_starfall', 'judgment_day', 'final_cut', 'silver_storm'])")
        expect(stateSource).toContain(".filter((entry) => entry.effectType !== 'bleed')")
        expect(stateSource).toContain('.slice(0, 10)')
        expect(stateSource).toContain("triggerDamageBurst(`boss-part:${event.partX}-${event.partY}`, {")
        expect(stateSource).toContain("damageType: 'magic'")
        expect(stateSource).toContain('triggerTalentEventDamageBursts(payload.talentEvents)')
        expect(battleSource).toContain('zoneBleedBursts(zone)')
    })

    it('重甲格子有金属质感和低频扫光，只作用在 5x5 战斗格子', () => {
        expect(styleSource).toContain('.boss-part-cell--heavy::after')
        expect(styleSource).toContain('animation: boss-heavy-sheen 3.6s ease-in-out infinite;')
        expect(styleSource).toContain('@keyframes boss-heavy-sheen')
        expect(styleSource).not.toContain('overflow: hidden;\n  border-color: rgba(148, 163, 184, 0.72);')
        expect(styleSource).toContain('.boss-zone-button--damage {')
        expect(styleSource).toContain('z-index: 30;')
        expect(styleSource).toContain('.boss-zone-button__damage-layer {')
        expect(styleSource).toContain('z-index: 24;')
        expect(styleSource).toContain('.boss-zone-button__damage-burst {')
        expect(styleSource).toContain('z-index: 25;')
        expect(styleSource).toContain('.boss-zone-button__damage-particle {')
        expect(styleSource).toContain('z-index: 14;')
        expect(styleSource).not.toContain('.boss-part-info__item--heavy::after')
    })
})

describe('伤害动画解析优先级文档', () => {
    it('补充说明文档并记录当前前端优先级', () => {
        expect(existsSync(docsPath)).toBe(true)
        const docsSource = readFileSync(docsPath, 'utf8')
        expect(stateSource).toContain("const DAMAGE_PRIORITY = ['doomsday', 'judgement', 'weakCritical', 'critical', 'trueDamage', 'magic', 'pursuit', 'heavy', 'physicalInvalid', 'normal']")
        expect(docsSource).toContain('doomsday -> judgement -> weakCritical -> critical -> trueDamage -> magic -> pursuit -> heavy -> physicalInvalid -> normal')
        expect(docsSource).toContain('普通命中重甲')
        expect(docsSource).toContain('物理无效化提示')
        expect(docsSource).toContain('10%')
        expect(docsSource).toContain('崩塌')
        expect(docsSource).toContain('resolveDamageVariant')
        expect(docsSource).toContain('triggerDamageBurst')
    })
})
