import {readFileSync} from 'node:fs'
import path from 'node:path'
import {fileURLToPath} from 'node:url'

import {describe, expect, it} from 'vitest'

const currentDir = path.dirname(fileURLToPath(import.meta.url))
const battleSource = readFileSync(path.resolve(currentDir, './BattlePage.vue'), 'utf8')
const canvasSource = readFileSync(path.resolve(currentDir, '../components/PixelEffectCanvas.vue'), 'utf8')
const styleSource = readFileSync(path.resolve(currentDir, '../style.css'), 'utf8')
const publicPageStateSource = readFileSync(path.resolve(currentDir, './publicPageState.js'), 'utf8')
const realtimeProtoSource = readFileSync(path.resolve(currentDir, '../proto/realtime.js'), 'utf8')

describe('BattlePage 战斗特效覆盖层', () => {
    it('战斗页把瞬发特效收口到单一 Canvas 管理器，不再直接挂多个 PixelEffectCanvas 实例', () => {
        expect(battleSource).toContain('const battleEffectEntries = computed(() => {')
        expect(battleSource).toContain('<PixelEffectCanvas')
        expect(battleSource).toContain(':entries="battleEffectEntries"')
        expect(battleSource).toContain(':canvas-width="talentOverlayCanvasSize.width"')
        expect(battleSource).toContain(':canvas-height="talentOverlayCanvasSize.height"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="storm_combo"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="auto_strike"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="bleed"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="final_cut"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="collapse_trigger"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="judgment_day"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="magic_burst"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="magic_rupture"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="magic_starfall"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="doom_mark"')
        expect(battleSource).not.toContain('<PixelEffectCanvas effect="silver_storm"')
    })

    it('点击热路径不再通过 offsetWidth 强制重排，也不再 appendChild DOM 粒子', () => {
        expect(battleSource).not.toContain('offsetWidth')
        expect(battleSource).not.toContain('document.body.appendChild')
        expect(battleSource).toContain('const clickSparkEntries = computed(() => {')
        expect(battleSource).toContain('queueClickSpark(')
        expect(battleSource).toContain('queueHitFlash(')
        expect(battleSource).toContain('const bossZoneElementMap = new Map()')
        expect(battleSource).toContain('spreadSize')
        expect(battleSource).toContain('width: entry.spreadSize')
        expect(battleSource).toContain('height: entry.spreadSize')
        expect(canvasSource).toContain('ctx.scale(instance.width / instance.size, instance.height / instance.size)')
        expect(canvasSource).not.toContain('ctx.clip()')
        expect(battleSource).toContain('const spreadSize = Math.max(effectCanvasSize(3.05), 156)')
    })

    it('统一特效 manager 不会因为 entries 数量变化而整层重启，避免长时特效被点击粒子打断重播', () => {
        expect(canvasSource).not.toContain('Array.isArray(props.entries) ? props.entries.length : -1')
        expect(canvasSource).toContain('watch(')
        expect(canvasSource).toContain('() => managerMode.value')
        expect(canvasSource).toContain('() => [props.effect, props.size, props.loop]')
        expect(canvasSource).toContain('function drawManagedFrame(ctx) {')
        expect(canvasSource).toContain('syncManagedEffects()')
        expect(canvasSource).toContain('const retiredManagedEffectIds = new Set()')
        expect(canvasSource).toContain('retiredManagedEffectIds.has(id)')
        expect(canvasSource).toContain('retiredManagedEffectIds.add(id)')
        expect(canvasSource).toContain('for (const id of retiredManagedEffectIds) {')
        expect(canvasSource).toContain('retiredManagedEffectIds.delete(id)')
    })

    it('统一特效 manager 不会因为画布宽高更新而 stop/start 重启整层，避免点击时长特效被清空或在窗口期内重生', () => {
        expect(canvasSource).not.toContain('() => [props.effect, props.size, props.loop, props.canvasWidth, props.canvasHeight, managerMode.value]')
        expect(canvasSource).toContain('() => managerMode.value')
        expect(canvasSource).toContain('if (managerMode.value) return')
        expect(canvasSource).toContain('() => [props.effect, props.size, props.loop]')
    })

    it('左侧状态列宽度更充裕，并与 5x5 战斗区保留明确间距', () => {
        expect(styleSource).toContain('.boss-left-panels {')
        expect(styleSource).toContain('left: max(0px, calc(50% - 518px));')
        expect(styleSource).toContain('width: 220px;')
        expect(styleSource).toContain('@media (max-width: 960px) {')
        expect(styleSource).toContain('.boss-left-panels {\n        left: 0;\n        width: 190px;\n    }')
    })

    it('瞬发特效尺寸按格子边长倍率换算，而不是继续写死像素值', () => {
        expect(battleSource).toContain('const bossCellSizePx = ref(56)')
        expect(battleSource).toContain('function measureBossCellSize() {')
        expect(battleSource).toContain("const cell = grid?.querySelector?.('.boss-part-cell')")
        expect(battleSource).toContain('function effectCanvasSize(scale) {')
        expect(battleSource).toContain('function ultimateEffectCanvasSize() {')
        expect(battleSource).toContain('Math.round(bossCellSizePx.value * scale)')
        expect(battleSource).toContain("pushBattleEffect(entries, 'storm_combo', {")
        expect(battleSource).toContain('size: effectCanvasSize(1.65)')
        expect(battleSource).toContain("pushBattleEffect(entries, 'auto_strike', {")
        expect(battleSource).toContain('size: effectCanvasSize(2.05)')
        expect(battleSource).toContain("pushBattleEffect(entries, 'bleed', {")
        expect(battleSource).toContain('size: effectCanvasSize(2.6)')
        expect(battleSource).toContain("pushBattleEffect(entries, 'final_cut', {")
        expect(battleSource).toContain('size: ultimateEffectCanvasSize()')
        expect(battleSource).toContain("pushBattleEffect(entries, 'collapse_trigger', {")
        expect(battleSource).toContain('size: effectCanvasSize(5)')
        expect(battleSource).toContain("pushBattleEffect(entries, 'judgment_day', {")
        expect(battleSource).toContain('size: bossGridEffectSize()')
        expect(styleSource).toContain('image-rendering: pixelated;')
    })

    it('每种特效仍保留独立锚点，但偏移改为按格子边长比例换算', () => {
        expect(battleSource).toContain('function effectOverlayStyle(type, options = {}) {')
        expect(battleSource).toContain('function resolveFallbackAnchor(fallback = {}) {')
        expect(battleSource).toContain("const center = gridOverlayAnchor()")
        expect(battleSource).not.toContain("const center = gridOverlayAnchor() || resolveFallbackAnchor(fallback)")
        expect(battleSource).toContain("width: width > 0 ? `${Math.round(width)}px` : undefined")
        expect(battleSource).toContain("height: height > 0 ? `${Math.round(height)}px` : undefined")
        expect(battleSource).toContain("effectOverlayStyle('storm_combo', { scale: 1.65, fallback:")
        expect(battleSource).not.toContain("effectOverlayStyle('auto_strike', { scale: 2.05, fallback:")
        expect(battleSource).toContain('for (const entry of recentBleedTriggers(BLEED_EFFECT_WINDOW_MS)) {')
        expect(battleSource).toContain("effectEntryLayout('bleed', {scale: 2.6, entryOverride: entry, fallback: { top: '50%', left: '50%' }})")
        expect(battleSource).toContain("effectOverlayStyle('final_cut', { anchor: 'grid', fallback:")
        expect(battleSource).toContain("effectOverlayStyle('collapse_trigger', { scale: 2, fallback:")
    })

    it('终末血斩改为直接驱动 5x5 战斗区的贯穿终结斩特效', () => {
        expect(battleSource).toContain('const ULTIMATE_EFFECT_WINDOW_MS = 3200')
        expect(battleSource).toContain("hasRecentTrigger('final_cut', ULTIMATE_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("effectOverlayStyle('final_cut', { anchor: 'grid', fallback:")
        expect(battleSource).toContain("pushBattleEffect(entries, 'final_cut', {")
    })

    it('流血改为按事件列表并发叠加渲染，而不是只取最新一层覆盖旧层', () => {
        expect(battleSource).toContain('for (const entry of recentBleedTriggers(BLEED_EFFECT_WINDOW_MS)) {')
        expect(battleSource).not.toContain("hasRecentTrigger('bleed')")
        expect(battleSource).toContain('id: entry.id')
        expect(battleSource).toContain('function triggerAnchor(type, windowMs = TALENT_EFFECT_WINDOW_MS, entryOverride = null) {')
        expect(battleSource).toContain("const BLEED_EFFECT_WINDOW_MS = 1200")
        expect(battleSource).toContain('function recentBleedTriggers(windowMs = BLEED_EFFECT_WINDOW_MS) {')
        expect(battleSource).toContain("return bleedTriggerFeed.value.filter((entry) => isTriggerFresh(entry, windowMs)).slice(0, 12)")
    })

    it('审判日在战斗页使用独立更长的挂载窗口，避免比 demo 提前卸载', () => {
        expect(battleSource).toContain('const JUDGMENT_DAY_EFFECT_WINDOW_MS = 5000')
        expect(battleSource).toContain("hasRecentTrigger('judgment_day', JUDGMENT_DAY_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("triggerKey('judgment_day', JUDGMENT_DAY_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("effectOverlayStyle('judgment_day', { anchor: 'grid', fallback: { top: '50%', left: '50%' } })")
        expect(battleSource).toContain("pushBattleEffect(entries, 'judgment_day', {")
    })

    it('魔法系特效正式挂到真实战斗页，并区分单格与 5x5 覆盖层', () => {
        expect(battleSource).toContain('const MAGIC_BURST_EFFECT_WINDOW_MS = 1600')
        expect(battleSource).toContain('const MAGIC_RUPTURE_EFFECT_WINDOW_MS = 1800')
        expect(battleSource).toContain("hasRecentTrigger('magic_burst', MAGIC_BURST_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("triggerKey('magic_burst', MAGIC_BURST_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("pushBattleEffect(entries, 'magic_burst', {")
        expect(battleSource).toContain("hasRecentTrigger('magic_rupture', MAGIC_RUPTURE_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("triggerKey('magic_rupture', MAGIC_RUPTURE_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("pushBattleEffect(entries, 'magic_rupture', {")
        expect(battleSource).toContain("const STARFALL_EFFECT_WINDOW_MS = 9200")
        expect(battleSource).toContain("hasRecentTrigger('magic_starfall', STARFALL_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("triggerKey('magic_starfall', STARFALL_EFFECT_WINDOW_MS)")
        expect(battleSource).toContain("pushBattleEffect(entries, 'magic_starfall', {")
    })

    it('左侧部位累计进度加入回响层数显示，右侧图例加入魔法伤害说明', () => {
        expect(battleSource).toContain('回响层数 {{ p.magic }}/{{ p.magicTrigger }}')
        expect(battleSource).toContain('潮爆 {{ p.magicTriggered }}/{{ p.magicUltimateTrigger }}')
        expect(battleSource).toContain('v-if="p.magic > 0"')
        expect(battleSource).toContain('v-if="p.magicTriggered > 0"')
        expect(battleSource).toContain('part-progress-panel__track--magic')
        expect(battleSource).toContain('part-progress-panel__track--magic-ultimate')
        expect(battleSource).toContain('part-progress-panel__bar-fill--magic')
        expect(battleSource).toContain('part-progress-panel__bar-fill--magic-ultimate')
        expect(battleSource).toContain('boss-right-legend__item boss-right-legend__item--magic')
        expect(battleSource).toContain('魔法伤害')
        expect(styleSource).toContain('.boss-right-legend__item--magic {')
        expect(styleSource).toContain('.boss-zone-button__damage-burst--magic {')
        expect(publicPageStateSource).toContain('magic: {')
        expect(publicPageStateSource).toContain("magic_damage: 'magic'")
        expect(publicPageStateSource).toContain("effectType === 'magic_burst'")
    })

    it('左侧全局状态加入回响刻印和星陨潮爆的累计与冷却显示', () => {
        expect(publicPageStateSource).toContain("key: 'magic-echo'")
        expect(publicPageStateSource).toContain("title: '回响刻印'")
        expect(publicPageStateSource).toContain("kind: 'magic_echo'")
        expect(publicPageStateSource).toContain("key: 'magic-ultimate'")
        expect(publicPageStateSource).toContain("title: '星陨潮爆'")
        expect(publicPageStateSource).toContain("kind: 'magic_ultimate'")
        expect(publicPageStateSource).toContain('if (magicEchoRequiredHits > 0 && (magicEchoStacks > 0 || magicEchoActive || magicEchoCooldownRemaining > 0)) {')
        expect(publicPageStateSource).toContain('? `CD 剩余 ${magicEchoCooldownRemaining}s`')
        expect(publicPageStateSource).toContain('if (magicUltimateTrigger > 0 && (magicUltimateBestCount > 0 || magicUltimateCooldownRemaining > 0)) {')
        expect(styleSource).toContain('.status-panel--magic_echo')
        expect(styleSource).toContain('.status-panel--magic_ultimate')
        expect(styleSource).toContain('.status-panel__bar-fill--magic_echo')
        expect(styleSource).toContain('.status-panel__bar-fill--magic_ultimate')
    })

    it('连击条颜色会随层数平滑渐变，而不是只在 200 层时才整体跳成金色', () => {
        expect(publicPageStateSource).toContain('const comboBarLeadColor = `hsl(${comboHue}, 92%,')
        expect(publicPageStateSource).toContain('const comboBarTailColor = `hsl(${Math.max(0, comboHue - 18)}, 96%,')
        expect(publicPageStateSource).toContain("background: comboIsGold ? `linear-gradient(90deg, ${comboGoldGradientStops.join(', ')})` : `linear-gradient(90deg, ${comboBarLeadColor}, ${comboColor}, ${comboBarTailColor})`")
    })

    it('星陨潮爆在真实战斗页沿用图鉴页同款低分辨率 5x5 画布，不直接按网格原始像素重算内部粒度', () => {
        expect(battleSource).toContain("pushBattleEffect(entries, 'magic_starfall', {")
        expect(battleSource).toContain('size: ultimateEffectCanvasSize()')
    })

    it('星陨潮爆自身时间轴被拉长，落地后会继续扩散和收尾，但仍然保持非循环播放', () => {
        expect(canvasSource).toContain("if (s.timer > 420) {")
        expect(canvasSource).toContain('const progress = Math.min(1, s.timer / 2600)')
        expect(canvasSource).toContain('p.life -= 0.01')
        expect(canvasSource).toContain("return s.phase === 'done' && s.timer > 300")
        expect(canvasSource).not.toContain('if (s.phase === \'freeze\' && s.timer > 3500) return this.init(size)')
    })

    it('实时二进制协议同步包含魔法战斗态字段，避免动画有了但层数和 CD 丢失', () => {
        expect(realtimeProtoSource).toContain('TalentCombatState.prototype.magicEchoTargetPart')
        expect(realtimeProtoSource).toContain('TalentCombatState.prototype.magicEchoRequiredHits')
        expect(realtimeProtoSource).toContain('TalentCombatState.prototype.magicUltimateTrigger')
        expect(realtimeProtoSource).toContain('TalentCombatState.prototype.partMagicTriggerCount')
    })

    it('流血以格子中心为喷发源，终末血斩的终结斩回退到更细一版的 5x5 对角重斩', () => {
        expect(canvasSource).toContain('const cx = size / 2, cy = size / 2')
        expect(canvasSource).toContain('for (let i = 0; i < 24; i++)')
        expect(canvasSource).toContain('const ang = Math.random() * Math.PI * 2, dist = Math.random() * 20')
        expect(canvasSource).toContain('return s.phase === \'done\' && s.timer > 1400')
        expect(canvasSource).toContain('const startX = -size * 0.32')
        expect(canvasSource).toContain('const endX = size * 1.32')
        expect(canvasSource).toContain('for (let w = -7; w <= 7; w++)')
        expect(canvasSource).toContain('sx + normalX * w * 4.8 + rnd(1.8)')
        expect(canvasSource).toContain('dist <= 1 ? 7 : dist <= 4 ? 6 : 4')
        expect(canvasSource).toContain('for (let w = -14; w <= 14; w += 3)')
        expect(canvasSource).toContain('for (const p of s.slashPixels) p.life -= 0.018')
        expect(canvasSource).toContain('sw.life -= 0.022')
        expect(canvasSource).toContain('sp.life -= 0.026')
    })

    it('战斗页保留房间伤害榜，大厅页保留点击总榜入口', () => {
        expect(battleSource).toContain('Boss 伤害榜')
        expect(battleSource).toContain('点击总榜')
        expect(battleSource).toContain('isHallRoom')
        expect(battleSource).toContain('bossLeaderboard.length')
        expect(battleSource).toContain('leaderboard.length')
    })

    it('崩塌只保留覆盖层瞬发特效，不再在格子内部重复渲染 PixelShatter', () => {
        expect(battleSource).toContain("pushBattleEffect(entries, 'collapse_trigger', {")
        expect(battleSource).not.toContain('<PixelShatter')
    })

    it('崩塌特效维持 5 倍覆盖层，并把内部扩散范围提到 0.85', () => {
        expect(battleSource).toContain("effectOverlayStyle('collapse_trigger', { scale: 2, fallback:")
        expect(battleSource).toContain("pushBattleEffect(entries, 'collapse_trigger', {")
        expect(canvasSource).toContain('const impactX = size / 2')
        expect(canvasSource).toContain('const impactY = size / 2')
        expect(canvasSource).toContain('const pivotX = impactX - handleLen')
        expect(canvasSource).toContain('const pivotY = impactY')
        expect(canvasSource).toContain('const collapseTriggerTickMs = 20')
        expect(canvasSource).toContain('const collapseTriggerSpeedScale = 1.25')
        expect(canvasSource).toContain('const collapseTriggerSpreadRatio = 0.85')
        expect(canvasSource).toContain('s.timer += collapseTriggerTickMs')
        expect(canvasSource).toContain('const speed = (0.6 + Math.random() * 2) * collapseTriggerSpeedScale')
        expect(canvasSource).toContain('const spreadRadius = size * collapseTriggerSpreadRatio')
        expect(canvasSource).toContain('const distFromCenter = Math.hypot(p.x - cx, p.y - cy)')
        expect(canvasSource).toContain('p.x += p.vx;')
        expect(canvasSource).toContain('p.y += p.vy;')
        expect(canvasSource).toContain('p.vx *= 0.992;')
        expect(canvasSource).toContain('p.vy *= 0.992')
        expect(canvasSource).toContain('else if (distFromCenter >= spreadRadius) p.life -= 0.02')
        expect(canvasSource).toContain('else if (s.timer > 520) p.life -= 0.006')
    })

    it('特效覆盖层层级高于点击格子和伤害数字，不再被战斗格子遮挡', () => {
        expect(styleSource).toContain('.boss-zone-button--damage {')
        expect(styleSource).toContain('z-index: 30;')
        expect(styleSource).toContain('.talent-effect-overlay {')
        expect(styleSource).toContain('z-index: 40;')
        expect(styleSource).toContain('.talent-canvas-fx {')
        expect(styleSource).toContain('z-index: 41;')
    })
})
