const OSS_EFFECT_BASE_URL = 'https://hai-world2.oss-cn-beijing.aliyuncs.com/effects'

const talentEffectFiles = [
    'talent-armor-t1a.png',
    'talent-armor-t1b.png',
    'talent-armor-t2a.png',
    'talent-armor-t2b.png',
    'talent-armor-t3a.png',
    'talent-armor-t3b.png',
    'talent-armor_auto_strike.png',
    'talent-armor_boss_hunter.png',
    'talent-armor_collapse_ext.png',
    'talent-armor_core.png',
    'talent-armor_heavy_atk.png',
    'talent-armor_heavy_scale.png',
    'talent-armor_pen_convert.png',
    'talent-armor_pen_up.png',
    'talent-armor_ruin.png',
    'talent-armor_ultimate.png',
    'talent-crit-t1a.png',
    'talent-crit-t1b.png',
    'talent-crit-t2a.png',
    'talent-crit-t2b.png',
    'talent-crit-t3a.png',
    'talent-crit-t3b.png',
    'talent-crit_bleed.png',
    'talent-crit_core.png',
    'talent-crit_cruel.png',
    'talent-crit_death_ecstasy.png',
    'talent-crit_final_cut.png',
    'talent-crit_omen_kill.png',
    'talent-crit_omen_reap.png',
    'talent-crit_omen_resonate.png',
    'talent-crit_skinner.png',
    'talent-crit_ultimate.png',
    'talent-crit_weakspot_insight.png',
    'talent-normal-t1a.png',
    'talent-normal-t1b.png',
    'talent-normal-t2a.png',
    'talent-normal-t2b.png',
    'talent-normal-t3a.png',
    'talent-normal-t3b.png',
    'talent-normal_atk_up.png',
    'talent-normal_charge.png',
    'talent-normal_chase_up.png',
    'talent-normal_combo_ext.png',
    'talent-normal_core.png',
    'talent-normal_dmg_amp.png',
    'talent-normal_encircle.png',
    'talent-normal_low_hp.png',
    'talent-normal_soft_atk.png',
    'talent-normal_ultimate.png',
]

export const effectAssetMap = Object.fromEntries(
    talentEffectFiles.map((filename) => [filename, `${OSS_EFFECT_BASE_URL}/${filename}`]),
)

effectAssetMap['talent-crit_doom_judgment.png'] = `${OSS_EFFECT_BASE_URL}/talent-crit_omen_resonate.png`
